// ============================================================================
// SERVICE WORKER — PWA shell/runtime cache and independently revised assets.
// Gameplay state and domain rules never belong here.
// ============================================================================
const BUILD_ID='cross-scope-journey-1';
const CACHE='eirdan-shell-v9-'+BUILD_ID;
const ASSET_CACHE='eirdan-assets-v2';
const CORE=['./','./app/index.html','./app/shell.css','./app/bootstrap.js','./app/navigation.js','./app/lifecycle.js','./app/game-screen.js','./app/modal.js','./app/notifications.js','./client/release.js','./client/update-manager.js','./client/asset-loader.js','./client/asset-cache.js','./client/integrity.js','./client/settings.js','./client/pwa.js','./diagnostics/action-diagnostics.js','./diagnostics/runtime-trace.js','./diagnostics/zip.js','./diagnostics/archive.js','./diagnostics/uploader.js','./diagnostics/format.js','./audio/catalog.js','./audio/context.js','./audio/player.js','./audio/effects.js','./audio/environment.js','./audio/system.js','./audio/diagnostics.js','./ui/world.js','./ui/map-ui.js','./ui/map-points.js','./tools/map-editor/road-editor.js','./tools/map-editor/editor-ui.js','./tools/map-editor/editor-runtime.js','./tools/map-editor/panel.js','./tools/map-editor/controller.js','./tools/map-editor/session.js','./tools/map-editor/poi-authoring.js','./tools/map-editor/terrain-editor.js','./tools/map-editor/terrain-store.js','./map/terrain.js','./map/poi-store.js','./map/view-state.js','./map/access-points.js','./tools/map-editor/export-data.js','./systems/travel/travel.js','./systems/travel/location-travel.js','./systems/travel/location-boundary.js','./systems/travel/journey.js','./systems/travel/roads.js','./systems/travel/route-planner.js','./systems/travel/conditions.js','./data/map-metrics.js','./systems/game-speed.js','./ui/map-gestures.js','./data/world.js','./data/regions/central-lands.js','./data/regions/central-lands-roads.js','./systems/pause.js','./data/locations/veligrad.js','./data/locations/veligrad-navigation.js','./core/session.js','./core/persistence.js','./diagnostics/shell-diagnostics.js','./diagnostics/travel-diagnostics.js','./diagnostics/ui-smoke-diagnostics.js','./manifest.webmanifest'];
const CRITICAL_ASSETS=[];
self.addEventListener('install',event=>event.waitUntil((async()=>{const cache=await caches.open(CACHE);for(const path of CORE){const req=new Request(path+'?build='+encodeURIComponent(BUILD_ID),{cache:'reload'});const res=await fetch(req);if(!res.ok)throw new Error('precache '+path+' '+res.status);await cache.put(path,res)}for(const path of CRITICAL_ASSETS){const req=new Request(path+'?build='+encodeURIComponent(BUILD_ID),{cache:'reload'});const res=await fetch(req);if(!res.ok)throw new Error('critical asset precache '+path+' '+res.status);await cache.put(path,res)}await self.skipWaiting()})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{for(const key of await caches.keys())if(key.startsWith('eirdan-shell-')&&key!==CACHE)await caches.delete(key);await self.clients.claim();for(const client of await self.clients.matchAll({type:'window'}))client.postMessage({type:'SW_ACTIVATED',build:BUILD_ID})})()));
self.addEventListener('message',event=>{if(event.data?.type==='CHECK_UPDATE')event.waitUntil(self.registration.update());if(event.data?.type==='SKIP_WAITING')self.skipWaiting();if(event.data?.type==='GET_BUILD')event.source?.postMessage({type:'SW_BUILD',build:BUILD_ID})});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==location.origin)return;
  if(url.pathname.includes('/assets/')){event.respondWith((async()=>{if(url.searchParams.has('rev'))return fetch(event.request,{cache:'no-store'});const cache=await caches.open(ASSET_CACHE),cached=await cache.match(event.request,{ignoreSearch:true});if(cached)return cached;try{return await fetch(event.request,{cache:'no-cache'})}catch{return Response.error()}})());return}
  if(url.pathname.endsWith('/client/asset-manifest.json')||url.pathname.endsWith('/data/version.json')||url.pathname.endsWith('/data/changelog.json')){event.respondWith(fetch(event.request,{cache:'no-store'}));return}
  event.respondWith((async()=>{const runtime=/\.(?:js|css|html)$/.test(url.pathname)||url.pathname.endsWith('/game/');if(runtime){try{const fresh=await fetch(event.request,{cache:'no-store'});if(fresh.ok){const cache=await caches.open(CACHE);await cache.put(event.request,fresh.clone())}return fresh}catch{const cached=await caches.match(event.request,{ignoreSearch:true});return cached||Response.error()}}const cached=await caches.match(event.request,{ignoreSearch:true});if(cached)return cached;try{const fresh=await fetch(event.request,{cache:'no-cache'});if(fresh.ok){const cache=await caches.open(CACHE);await cache.put(event.request,fresh.clone())}return fresh}catch{return Response.error()}})())});
