const BUILD_ID='animated-travel-1';
const CACHE='eirdan-shell-v6-'+BUILD_ID;
const CORE=['./','./app/index.html','./app/shell.css','./app/bootstrap.js','./app/navigation.js','./app/lifecycle.js','./app/game-screen.js','./client/release.js','./client/update-manager.js','./diagnostics/action-diagnostics.js','./diagnostics/uploader.js','./diagnostics/format.js','./ui/world.js','./systems/world.js','./data/world.js','./data/regions/central-lands.js','./data/regions/central-lands-roads.js','./systems/roads.js','./systems/pause.js','./systems/travel.js','./data/locations/veligrad.js','./core/session.js','./core/persistence.js','./diagnostics/shell-diagnostics.js','./manifest.webmanifest'];
const OPTIONAL=['./assets/world/eirdan-world-map-regions-final.png','./assets/world/eirdan-world-region-index-final.png','./assets/regions/region-central-lands.png','./assets/locations/city-01-central-lands.png'];
self.addEventListener('install',event=>event.waitUntil((async()=>{const cache=await caches.open(CACHE);for(const path of CORE){const req=new Request(path+'?build='+encodeURIComponent(BUILD_ID),{cache:'reload'});const res=await fetch(req);if(!res.ok)throw new Error('precache '+path+' '+res.status);await cache.put(path,res)}for(const path of OPTIONAL){try{const req=new Request(path+'?build='+encodeURIComponent(BUILD_ID),{cache:'reload'});const res=await fetch(req);if(res.ok)await cache.put(path,res)}catch(error){console.warn('optional precache failed',path,error)}}await self.skipWaiting()})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{for(const key of await caches.keys())if(key.startsWith('eirdan-shell-')&&key!==CACHE)await caches.delete(key);await self.clients.claim();for(const client of await self.clients.matchAll({type:'window'}))client.postMessage({type:'SW_ACTIVATED',build:BUILD_ID})})()));
self.addEventListener('message',event=>{if(event.data?.type==='CHECK_UPDATE')event.waitUntil(self.registration.update());if(event.data?.type==='SKIP_WAITING')self.skipWaiting();if(event.data?.type==='GET_BUILD')event.source?.postMessage({type:'SW_BUILD',build:BUILD_ID})});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==location.origin)return;
  if(url.pathname.endsWith('/ui/build.json')||url.pathname.endsWith('/data/version.json')||url.pathname.endsWith('/data/changelog.json')){event.respondWith(fetch(event.request,{cache:'no-store'}));return}
  event.respondWith((async()=>{try{const fresh=await fetch(event.request,{cache:'no-cache'});if(fresh.ok){const cache=await caches.open(CACHE);await cache.put(event.request,fresh.clone())}return fresh}catch{const cached=await caches.match(event.request,{ignoreSearch:true});return cached||Response.error()}})())});
