const KEY='eyrdan_pwa_v2', CREATOR_KEY='eyrdan_creator_v2';
const initial={day:1,minutes:480,place:'Опушка у деревни Эйрдан',hero:{name:'Безымянный герой',race:'человек',age:24,hp:20,maxHp:20,stats:{Сила:10,Ловкость:10,Выносливость:10,Разум:10},conditions:{Голод:'нет',Жажда:'нет',Усталость:'нет',Боль:'нет'},skills:['Наблюдательность','Атлетика']},inventory:['Потрёпанный плащ','Фляга воды','Нож'],places:['Деревня Эйрдан','Старый тракт','Тёмный лес','Ручей'],story:[{r:'gm',t:'Ты стоишь на поросшей мхом дороге у ворот небольшой деревни. Впереди спорят стражник и запылённый торговец; справа журчит ручей, слева темнеет лес.'}],choices:['Подойти к стражнику и торговцу','Зайти в деревню','Осмотреть край леса','Подойти к ручью']};
let s=load(); let creator=loadCreator();
function loadCreator(){try{return JSON.parse(localStorage.getItem(CREATOR_KEY))||null}catch{return null}}
function creatorComplete(x){return !!(x&&x.name&&x.race&&x.stats)}function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(initial)}catch{return structuredClone(initial)}}function save(){localStorage.setItem(KEY,JSON.stringify(s))}
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
function time(){return String(Math.floor(s.minutes/60)%24).padStart(2,'0')+':'+String(s.minutes%60).padStart(2,'0')}
function advance(n){s.minutes+=n;while(s.minutes>=1440){s.minutes-=1440;s.day++}save();render()}
function mockGM(a){const x=a.toLowerCase();let t='Ты выполняешь задуманное. Мир отвечает на действие без резкого скачка времени или событий.';let c=['Осмотреться внимательнее','Продолжить','Вернуться к дороге'];if(x.includes('руч')){s.place='Берег ручья';t='Ты подходишь к холодному ручью. Вода прозрачная, течение быстрое. В мокрой земле видны свежие следы сапог.';c=['Осмотреть следы','Набрать воды','Вернуться к дороге']}else if(x.includes('лес')){s.place='Край Тёмного леса';t='Под кронами становится заметно тише. Между корней тянется узкая звериная тропа, а на коре одного дерева видна старая зарубка.';c=['Осмотреть зарубку','Пройти немного по тропе','Вернуться']}else if(x.includes('деревн')||x.includes('страж')){s.place='Ворота деревни Эйрдан';t='У ворот слышен разговор о сломанной телеге на северном тракте. Стражник замечает тебя, но пока лишь наблюдает.';c=['Заговорить со стражником','Послушать торговца','Войти в деревню']}s.story.push({r:'player',t:a},{r:'gm',t});s.story=s.story.slice(-8);s.choices=c;advance(10)}
function act(a){a=String(a||'').trim();if(!a)return;$('#action').value='';mockGM(a)}
function renderCharacter(){
 creator=loadCreator(); const ok=creatorComplete(creator);
 $('#characterEmpty').classList.toggle('hidden',ok); $('#characterReady').classList.toggle('hidden',!ok);
 if(!ok)return;
 const raceNames={human:'Человек',elf:'Эльф',dwarf:'Дворф',halfelf:'Полуэльф',halfling:'Полурослик',orc:'Орк',half_orc:'Полуорк',gnome:'Гном',tiefling:'Тифлинг',beastkin:'Зверолюд'};
 const originNames={peasant:'Крестьянская семья',artisan:'Семья ремесленника',minor_noble:'Обедневшая знать',merchant:'Торговый дом',frontier:'Пограничное поселение',hunter:'Лесная окраина',military:'Военная семья',clergy:'При храме',underworld:'Улица и преступная среда',nomad:'Кочевой род',scholar:'Учёная среда',refugee:'Беженцы',sailor:'Портовая семья',orphan:'Сирота'};
 const pathNames={warrior:'Воин',hunter:'Охотник',rogue:'Ловкач',healer:'Лекарь',mage:'Ученик мага',mercenary:'Наёмник',scout:'Разведчик',craftsman:'Ремесленник',scholar:'Учёный',acolyte:'Послушник',bard:'Менестрель',traveler:'Странник',none:'Без специализации'};
 $('#heroName').textContent=creator.name; $('#heroMeta').textContent=(raceNames[creator.race]||creator.race)+' · '+creator.age+' лет';
 $('#stats').innerHTML=Object.entries(creator.stats||{}).map(([k,v])=>'<div class="tile"><b>'+escapeHtml(k)+'</b><div>'+v+'</div></div>').join('');
 $('#traits').innerHTML=(creator.traits||[]).map(x=>'<div class="row">'+escapeHtml(x)+'</div>').join('')||'<div class="muted">Черты не выбраны</div>';
 $('#heroBackground').innerHTML='<div class="row"><b>Происхождение</b><div class="muted">'+escapeHtml(originNames[creator.origin]||creator.origin||'—')+'</div></div><div class="row"><b>Путь</b><div class="muted">'+escapeHtml(pathNames[creator.path]||creator.path||'—')+'</div></div>';
}
function renderVisibility(){const v=localStorage.getItem('eyrdan_visibility')||(creator&&creator.visibilityMode)||'hybrid';$('[data-vis]').forEach(b=>b.classList.toggle('on',b.dataset.vis===v))}
function render(){ renderCharacter(); renderVisibility(); $('#clock').textContent='День '+s.day+' · '+time();$('#place').textContent=s.place;$('#story').innerHTML=s.story.map(x=>'<div class="bubble '+x.r+'">'+escapeHtml((x.r==='player'?'Вы: ':'')+x.t)+'</div>').join('');$('#choices').innerHTML=s.choices.map((x,i)=>'<button class="choice" data-choice="'+i+'">'+['А','Б','В','Г'][i]+') '+escapeHtml(x)+'</button>').join('');$$('[data-choice]').forEach(b=>b.onclick=()=>act(s.choices[+b.dataset.choice]));if(!creatorComplete(loadCreator())){ $('#heroName').textContent=s.hero.name; $('#heroMeta').textContent=s.hero.race+' · '+s.hero.age+' лет · HP '+s.hero.hp+'/'+s.hero.maxHp; $('#stats').innerHTML=Object.entries(s.hero.stats).map(([k,v])=>'<div class="tile"><b>'+k+'</b><div>'+v+'</div></div>').join(''); }$('#conditions').innerHTML=Object.entries(s.hero.conditions).map(([k,v])=>'<div class="tile"><b>'+k+'</b><div class="muted">'+v+'</div></div>').join('');$('#items').innerHTML=s.inventory.map(x=>'<div class="row">'+x+'</div>').join('');$('#places').innerHTML=s.places.map(x=>'<button class="row" style="width:100%;text-align:left" data-place="'+x+'">'+x+'</button>').join('');$$('[data-place]').forEach(b=>b.onclick=()=>{show('game');act('Отправиться: '+b.dataset.place)});save()}
function escapeHtml(x){return String(x).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}function show(id){if(id==='character')renderCharacter();if(id==='settings')renderVisibility();$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('#nav [data-page]').forEach(x=>x.classList.toggle('on',x.dataset.page===id))}
function openCreator(){location.href='./character-creator.html'}
$('#createHero').onclick=openCreator;$('#editHero').onclick=openCreator;
$('#visibilityModes').onclick=e=>{const b=e.target.closest('[data-vis]');if(!b)return;localStorage.setItem('eyrdan_visibility',b.dataset.vis);renderVisibility()};
window.addEventListener('pageshow',()=>{renderCharacter();renderVisibility()});
$('#nav').onclick=e=>{const b=e.target.closest('[data-page]');if(b)show(b.dataset.page)};$('#send').onclick=()=>act($('#action').value);$('#action').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();act(e.target.value)}};$('#advance').onclick=()=>advance(15);$('#reset').onclick=()=>{if(confirm('Сбросить локальный прототип?')){s=structuredClone(initial);save();render();show('game')}};render();