import assert from 'node:assert/strict';
import fs from 'node:fs';
import {GameState} from '../game/core/game-state.js';
import {createUnit} from '../game/data/unit-factory.js';
import {shieldBash,sweep} from '../game/combat/melee-skills.js';
const W=JSON.parse(fs.readFileSync(new URL('../game/data/weapons.json',import.meta.url)));
const s=new GameState(3);
const a=createUnit({id:'a',team:'ally',cls:'guardian',q:2,r:4});
const e=createUnit({id:'e',team:'enemy',cls:'guardian',q:3,r:4});
s.units=[a,e]; s.order=[a,e];
assert.equal(shieldBash(s,a,e,W,()=>.1).ok,true);
a.ap=9;
assert.equal(sweep(s,a,W,()=>.1).ok,true);
console.log('class skills: OK');
