import {verifyResponse} from './integrity.js';
export const ASSET_CACHE='eirdan-assets-v2';export const ASSET_MANIFEST_URL=new URL('./asset-manifest.json',import.meta.url).href;
function absolute(path){return new URL(path,import.meta.url).href}function revisionUrl(asset){const url=new URL(absolute(asset.path));url.searchParams.set('rev',asset.revision);return url.href}
async function decodeImage(response){const blob=await response.blob(),objectUrl=URL.createObjectURL(blob);try{const img=new Image();img.decoding='async';img.src=objectUrl;await img.decode()}finally{URL.revokeObjectURL(objectUrl)}}
async function validateAsset(response,asset){if(asset.sha256&&!await verifyResponse(response.clone(),asset.sha256))throw new Error('asset integrity '+asset.id);if(asset.type==='image')await decodeImage(response.clone())}
export async function loadAssetManifest(){const response=await fetch(ASSET_MANIFEST_URL+'?t='+Date.now(),{cache:'no-store'});if(!response.ok)throw new Error('asset manifest '+response.status);const manifest=await response.json();if(manifest.schema!==1||!Array.isArray(manifest.assets))throw new Error('asset manifest schema');return manifest}
async function removeOldRevisions(cache,asset,keepRequest){const target=new URL(absolute(asset.path)).pathname;for(const request of await cache.keys()){const url=new URL(request.url);if(url.pathname===target&&request.url!==keepRequest.url)await cache.delete(request)}}
export async function ensureAsset(cache,asset){const request=new Request(revisionUrl(asset),{cache:'reload'});let response=await cache.match(request);if(response){await validateAsset(response.clone(),asset);return{asset,status:'cached'}}const previous=(await cache.keys()).find(r=>new URL(r.url).pathname===new URL(absolute(asset.path)).pathname);try{response=await fetch(request);if(!response.ok)throw new Error('asset '+asset.id+' '+response.status);await validateAsset(response.clone(),asset);await cache.put(request,response.clone());await removeOldRevisions(cache,asset,request);return{asset,status:'updated'}}catch(error){if(previous){const fallback=await cache.match(previous);if(fallback){await validateAsset(fallback.clone(),asset);return{asset,status:'fallback',error:String(error)}}}throw error}}
export async function warmAssets({startupOnly=false,onProgress}={}){if(!('caches' in globalThis))return{ok:false,reason:'cache-api',loaded:0,total:0};const manifest=await loadAssetManifest(),assets=startupOnly?manifest.assets.filter(a=>a.startup):manifest.assets,cache=await caches.open(ASSET_CACHE);let loaded=0;const results=[];for(const asset of assets){results.push(await ensureAsset(cache,asset));loaded++;onProgress?.({loaded,total:assets.length,ratio:assets.length?loaded/assets.length:1,asset:asset.id})}return{ok:true,loaded,total:assets.length,results,manifest}}
export async function assetCacheStatus(){if(!('caches' in globalThis))return{ok:false,reason:'cache-api',expected:0,current:0,missing:[]};const manifest=await loadAssetManifest(),cache=await caches.open(ASSET_CACHE),keys=await cache.keys(),current=new Set(keys.map(r=>r.url));const missing=manifest.assets.filter(a=>!current.has(revisionUrl(a))).map(a=>a.id),stale=keys.filter(r=>!manifest.assets.some(a=>revisionUrl(a)===r.url)).map(r=>r.url);return{ok:missing.length===0,expected:manifest.assets.length,current:keys.length,missing,stale,cache:ASSET_CACHE}}
