function dist(a,b){return Math.hypot(b.x-a.x,b.y-a.y)}
function length(path){let n=0;for(let i=1;i<path.length;i++)n+=dist(path[i-1],path[i]);return n}
function closestOnSegment(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return{...a,t:0,distance:dist(p,a)};const t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l)),q={x:a.x+dx*t,y:a.y+dy*t};return{...q,t,distance:dist(p,q)}}
function v2Graph(roads){const nodes=new Map((roads.nodes||[]).map(n=>[n.id,n])),g=new Map();for(const [a,b,via=[]] of roads.edges||[]){const pa=nodes.get(a),pb=nodes.get(b);if(!pa||!pb)continue;const path=[pa,...via.map(([x,y])=>({x,y})),pb],w=length(path);for(const [from,to,rev] of [[a,b,false],[b,a,true]]){if(!g.has(from))g.set(from,[]);g.get(from).push({to,weight:w,path:rev?[...path].reverse():path})}}return{nodes,g}}
function shortest(g,from,to){if(from===to)return{nodeIds:[from],segments:[],polyline:[],distance:0};const best=new Map([[from,0]]),prev=new Map(),q=[[0,from]];while(q.length){q.sort((a,b)=>a[0]-b[0]);const [cost,id]=q.shift();if(cost!==best.get(id))continue;if(id===to)break;for(const e of g.get(id)||[]){const n=cost+e.weight;if(n<(best.get(e.to)??Infinity)){best.set(e.to,n);prev.set(e.to,{id,e});q.push([n,e.to])}}}if(!best.has(to))return null;const seg=[],ids=[to];let cur=to;while(cur!==from){const p=prev.get(cur);seg.unshift({from:p.id,to:cur,distance:p.e.weight,path:p.e.path});cur=p.id;ids.unshift(cur)}const poly=[];for(const s of seg)for(const p of s.path){const z=poly.at(-1);if(!z||z.x!==p.x||z.y!==p.y)poly.push({x:p.x,y:p.y})}return{nodeIds:ids,segments:seg,polyline:poly,distance:best.get(to)}}
function legacy(roads,points){const g=new Map();for(const [a,b,via=[]] of roads.edges||[]){const pa=points.find(p=>p.id===a),pb=points.find(p=>p.id===b);if(!pa||!pb)continue;const path=[pa,...via.map(([x,y])=>({x,y})),pb],w=length(path);for(const [from,to,rev] of [[a,b,false],[b,a,true]]){if(!g.has(from))g.set(from,[]);g.get(from).push({to,weight:w,path:rev?[...path].reverse():path})}}return g}
export const RoadSystem={
 graph(roads,points){return roads.version>=2?v2Graph(roads).g:legacy(roads,points)},
 route(roads,points,fromId,toId){if(roads.version<2){const r=shortest(legacy(roads,points),fromId,toId);return r?{fromId,toId,...r}:null}const {nodes,g}=v2Graph(roads),a=roads.access?.[fromId],b=roads.access?.[toId],pa=points.find(p=>p.id===fromId),pb=points.find(p=>p.id===toId);if(!a||!b||!pa||!pb)return null;const core=shortest(g,a.node,b.node);if(!core)return null;const na=nodes.get(a.node),nb=nodes.get(b.node),poly=[{x:pa.x,y:pa.y},{x:na.x,y:na.y},...core.polyline.slice(1),{x:pb.x,y:pb.y}],d=length(poly);return{fromId,toId,nodeIds:[fromId,...core.nodeIds,toId],roadNodeIds:core.nodeIds,segments:core.segments,polyline:poly,distance:d}},
 nearestRoadPoint(roads,pos){if(roads.version<2)return null;const {nodes}=v2Graph(roads);let best=null;for(const [a,b] of roads.edges||[]){const pa=nodes.get(a),pb=nodes.get(b);if(!pa||!pb)continue;const q=closestOnSegment(pos,pa,pb);if(!best||q.distance<best.distance)best={...q,a,b}}return best},
 routeFromPosition(roads,points,pos,toId){if(roads.version<2)return null;const snap=this.nearestRoadPoint(roads,pos),target=roads.access?.[toId],dest=points.find(p=>p.id===toId);if(!snap||!target||!dest)return null;const {nodes,g}=v2Graph(roads);const choices=[];for(const start of [snap.a,snap.b]){const core=shortest(g,start,target.node);if(core){const startNode=nodes.get(start);choices.push({core,start,cost:dist(snap,startNode)+core.distance})}}choices.sort((a,b)=>a.cost-b.cost);const c=choices[0];if(!c)return null;const startNode=nodes.get(c.start),endNode=nodes.get(target.node);const poly=[{...pos},{x:snap.x,y:snap.y},{x:startNode.x,y:startNode.y},...c.core.polyline.slice(1),{x:endNode.x,y:endNode.y},{x:dest.x,y:dest.y}];return{fromId:'road-position',toId,nodeIds:['road-position',c.start,...c.core.nodeIds.slice(1),toId],roadNodeIds:[c.start,...c.core.nodeIds.slice(1)],segments:c.core.segments,polyline:poly,distance:length(poly),roadEntry:{x:snap.x,y:snap.y,edge:[snap.a,snap.b]}}}
};
