import {RoadSystem} from './roads.js';
import {PauseSystem} from './pause.js';
function dist(a,b){return Math.hypot(b.x-a.x,b.y-a.y)}
function metrics(polyline){const lengths=[];let total=0;for(let i=1;i<(polyline?.length||0);i++){const n=dist(polyline[i-1],polyline[i]);lengths.push(n);total+=n}return{lengths,total}}
function atDistance(polyline,distance){if(!polyline?.length)return null;if(polyline.length===1)return{...polyline[0]};const {lengths,total}=metrics(polyline);let target=Math.max(0,Math.min(total,distance));for(let i=0;i<lengths.length;i++){if(target<=lengths[i]){const a=polyline[i],b=polyline[i+1],q=lengths[i]?target/lengths[i]:0;return{x:a.x+(b.x-a.x)*q,y:a.y+(b.y-a.y)*q}}target-=lengths[i]}return{...polyline.at(-1)}}
function atPolyline(polyline,t){const {total}=metrics(polyline);return atDistance(polyline,Math.max(0,Math.min(1,t))*total)}
function nearestVertex(polyline,pos){let best=null;for(let i=0;i<(polyline?.length||0);i++){const d=dist(polyline[i],pos);if(!best||d<best.distance)best={index:i,distance:d,point:polyline[i]}}return best}
function routeFromPosition(roads,points,pos,toId){const candidates=[];for(const p of points){const r=RoadSystem.route(roads,points,p.id,toId);if(r)candidates.push({p,r,cost:dist(pos,p)+r.distance})}candidates.sort((a,b)=>a.cost-b.cost);const best=candidates[0];if(!best)return null;return{...best.r,polyline:[{...pos},{...best.p},...best.r.polyline.slice(1)],distance:best.cost,nodeIds:[best.p.id,...best.r.nodeIds.slice(1)]}}
export const TravelSystem={
 ensure(state){state.world=state.world||{};state.world.travel=state.world.travel||{status:'idle'};return state.world.travel},
 start(state,{roads,points,fromId,toId,method='walk',fromPosition=null}){const route=fromPosition?routeFromPosition(roads,points,fromPosition,toId):RoadSystem.route(roads,points,fromId,toId);if(!route)return null;const t={status:'travelling',regionId:roads.regionId,fromId:fromPosition?'road-position':fromId,toId,method,progress:0,route,position:atPolyline(route.polyline,0),distanceDone:0,distanceTotal:route.distance};state.world.travel=t;return t},
 reroute(state,{roads,points,toId,method}){const old=this.ensure(state);if(!old.position||!old.route?.polyline?.length)return this.start(state,{roads,points,fromId:state.world?.position?.pointId||old.toId,toId,method:method||old.method});const snap=nearestVertex(old.route.polyline,old.position),candidates=[];for(const id of old.route.nodeIds||[]){const p=points.find(x=>x.id===id);if(!p)continue;const route=RoadSystem.route(roads,points,id,toId);if(route)candidates.push({id,p,route,cost:dist(old.position,p)+route.distance})}candidates.sort((a,b)=>a.cost-b.cost);const best=candidates[0];if(!best)return null;const route={...best.route,polyline:[{...old.position},{...best.p},...best.route.polyline.slice(1)],distance:best.cost,nodeIds:[best.id,...best.route.nodeIds.slice(1)]};const t={status:'travelling',regionId:roads.regionId,fromId:'road-position',toId,method:method||old.method,progress:0,route,position:{...old.position},distanceDone:0,distanceTotal:route.distance,rerouted:true,snapIndex:snap?.index??null};state.world.travel=t;return t},
 tick(state,deltaSeconds,speed=.025){const t=this.ensure(state);if(t.status!=='travelling'||PauseSystem.isPaused(state))return t;const before=t.progress;t.progress=Math.min(1,t.progress+Math.max(0,deltaSeconds)*speed);t.position=atPolyline(t.route.polyline,t.progress);t.deltaProgress=t.progress-before;t.distanceTotal=t.route.distance||metrics(t.route.polyline).total;t.distanceDone=t.distanceTotal*t.progress;if(t.progress>=1)t.status='arrived';return t},
 stop(state){const t=this.ensure(state);if(t.status==='travelling')t.status='stopped';return t},
 resume(state){const t=this.ensure(state);if(t.status==='stopped'||t.status==='camp')t.status='travelling';return t},
 camp(state){const t=this.ensure(state);if(t.position){t.status='camp';state.world.camp={regionId:t.regionId,position:{...t.position},createdAt:{day:state.clock.day,minute:state.clock.minute}}}return t},
 pauseForEvent(state,eventId){const t=this.ensure(state);if(t.status==='travelling')t.status='event';t.eventId=eventId||null;PauseSystem.set(state,'event',true);return t},
 resumeEvent(state){const t=this.ensure(state);PauseSystem.set(state,'event',false);if(t.status==='event'){t.status='travelling';t.eventId=null}return t},
 cancel(state){const t=this.ensure(state);if(t.position)state.world.position={regionId:t.regionId,pointId:null,position:{...t.position}};state.world.travel={status:'idle',position:t.position?{...t.position}:null,regionId:t.regionId||null};return state.world.travel},
 progress(state){const t=this.ensure(state),total=t.distanceTotal||t.route?.distance||0,done=total*(t.progress||0);return{done,total,left:Math.max(0,total-done),ratio:total?done/total:0}}
};
