import {RoadSystem} from './roads.js';
import {PauseSystem} from './pause.js';
import {runtimeTrace} from '../diagnostics/runtime-trace.js';
function dist(a,b){return Math.hypot(b.x-a.x,b.y-a.y)}
function metrics(polyline){const lengths=[];let total=0;for(let i=1;i<(polyline?.length||0);i++){const n=dist(polyline[i-1],polyline[i]);lengths.push(n);total+=n}return{lengths,total}}
function atDistance(polyline,distance){if(!polyline?.length)return null;if(polyline.length===1)return{...polyline[0]};const {lengths,total}=metrics(polyline);let target=Math.max(0,Math.min(total,distance));for(let i=0;i<lengths.length;i++){if(target<=lengths[i]){const a=polyline[i],b=polyline[i+1],q=lengths[i]?target/lengths[i]:0;return{x:a.x+(b.x-a.x)*q,y:a.y+(b.y-a.y)*q}}target-=lengths[i]}return{...polyline.at(-1)}}
function atPolyline(polyline,t){const {total}=metrics(polyline);return atDistance(polyline,Math.max(0,Math.min(1,t))*total)}
function nearestVertex(polyline,pos){let best=null;for(let i=0;i<(polyline?.length||0);i++){const d=dist(polyline[i],pos);if(!best||d<best.distance)best={index:i,distance:d,point:polyline[i]}}return best}
export const TravelSystem={
 ensure(state){state.world=state.world||{};state.world.travel=state.world.travel||{status:'idle'};return state.world.travel},
 start(state,{roads,points,fromId,toId,method='walk',fromPosition=null}){const trace=runtimeTrace.begin('travel.start',{fromId,toId,method,fromPosition});const route=fromPosition?RoadSystem.routeFromPosition(roads,points,fromPosition,toId):RoadSystem.route(roads,points,fromId,toId);if(!route){runtimeTrace.end(trace,{ok:false,reason:'no-route'});return null}const t={status:'travelling',regionId:roads.regionId,fromId:fromPosition?'road-position':fromId,toId,method,progress:0,route,position:atPolyline(route.polyline,0),distanceDone:0,distanceTotal:route.distance};state.world.travel=t;runtimeTrace.end(trace,{ok:true,distance:route.distance,nodeIds:route.nodeIds,roadEntry:route.roadEntry||null});return t},
 reroute(state,{roads,points,toId,method}){const trace=runtimeTrace.begin('travel.reroute',{toId,method});const old=this.ensure(state);if(!old.position)return this.start(state,{roads,points,fromId:state.world?.position?.pointId||old.toId,toId,method:method||old.method});const route=RoadSystem.routeFromPosition(roads,points,old.position,toId);if(!route){runtimeTrace.end(trace,{ok:false,reason:'no-route'});return null}const t={status:'travelling',regionId:roads.regionId,fromId:'road-position',toId,method:method||old.method,progress:0,route,position:{...old.position},distanceDone:0,distanceTotal:route.distance,rerouted:true};state.world.travel=t;runtimeTrace.end(trace,{ok:true,distance:route.distance,nodeIds:route.nodeIds,roadEntry:route.roadEntry||null});return t},
  tick(state,deltaSeconds,speed=.025){const t=this.ensure(state);if(t.status!=='travelling'||PauseSystem.isPaused(state))return t;const before=t.progress;t.progress=Math.min(1,t.progress+Math.max(0,deltaSeconds)*speed);t.position=atPolyline(t.route.polyline,t.progress);t.deltaProgress=t.progress-before;t.distanceTotal=t.route.distance||metrics(t.route.polyline).total;t.distanceDone=t.distanceTotal*t.progress;if(t.progress>=1){t.status='arrived';runtimeTrace.animation('travel.arrived',{toId:t.toId,position:t.position,distance:t.distanceTotal})}return t},
 stop(state){const t=this.ensure(state);runtimeTrace.system('travel.stop','invoke',{status:t.status,position:t.position});if(t.status==='travelling')t.status='stopped';return t},
 resume(state){const t=this.ensure(state);runtimeTrace.system('travel.resume','invoke',{status:t.status,position:t.position});if(t.status==='stopped'||t.status==='camp')t.status='travelling';return t},
 camp(state){const t=this.ensure(state);runtimeTrace.system('travel.camp','invoke',{status:t.status,position:t.position});if(t.position){t.status='camp';state.world.camp={regionId:t.regionId,position:{...t.position},createdAt:{day:state.clock.day,minute:state.clock.minute}}}return t},
 pauseForEvent(state,eventId){const t=this.ensure(state);if(t.status==='travelling')t.status='event';t.eventId=eventId||null;PauseSystem.set(state,'event',true);return t},
 resumeEvent(state){const t=this.ensure(state);PauseSystem.set(state,'event',false);if(t.status==='event'){t.status='travelling';t.eventId=null}return t},
 cancel(state){const t=this.ensure(state);runtimeTrace.system('travel.cancel','invoke',{status:t.status,position:t.position});if(t.position)state.world.position={regionId:t.regionId,pointId:null,position:{...t.position}};state.world.travel={status:'idle',position:t.position?{...t.position}:null,regionId:t.regionId||null};return state.world.travel},
 progress(state){const t=this.ensure(state),total=t.distanceTotal||t.route?.distance||0,done=total*(t.progress||0);return{done,total,left:Math.max(0,total-done),ratio:total?done/total:0}}
};
