import {WorldSystem} from '../systems/world/world.js';
import {el} from './map-ui.js';

export const MAP_POINT_CLASSES={location:'Локация',district:'Район',place:'Место',transition:'Переход'};
export const MAP_POINT_TYPES={city:'Город',village:'Поселение',fort:'Крепость',tower:'Башня',ruins:'Руины',mountain_pass:'Перевал',marsh:'Топи',landmark:'Ориентир',location:'Локация',district:'Район',place:'Место',transition:'Переход'};
const ICONS={city:'♜',village:'⌂',fort:'◆',tower:'▲',ruins:'✦',mountain_pass:'⌃',marsh:'≈',landmark:'◇',location:'○',district:'▦',place:'●',transition:'⇢'};

export function pointIcon(item){return ICONS[item.type]||ICONS[item.class]||'●'}
export function pointTypeLabel(item){return MAP_POINT_TYPES[item.type]||MAP_POINT_TYPES[item.class]||'Место'}
export function pointDescription(item){return item.description||({location:'Отдельная локация. Её можно посетить и исследовать.',district:'Район внутри текущей локации.',place:'Отдельное место на карте.',transition:'Переход к другой области карты.'}[item.class]||'Место на карте.')}
export function mapPointSlug(value){return String(value||'poi').toLowerCase().trim().replace(/[^a-zа-яё0-9]+/gi,'-').replace(/^-|-$/g,'').slice(0,48)||'poi'}
export function legendFor(items,state,editing){const visible=items.filter(point=>editing||WorldSystem.isDiscovered(state,point)),types=[...new Set(visible.map(point=>point.type||point.class))],box=el('details');box.className='map-legend';box.onclick=event=>event.stopPropagation();box.onpointerdown=event=>event.stopPropagation();box.append(el('summary','Легенда'));const body=el('div');body.className='map-legend-items';for(const type of types){const sample=visible.find(point=>(point.type||point.class)===type),row=el('div');row.append(el('span',pointIcon(sample)),el('span',pointTypeLabel(sample)));body.append(row)}box.append(body);return box}
export function actionPanel(item,state,onTravel,onFavorite){const box=el('section');box.className='map-point-card';const top=el('div');top.className='map-point-card-head';top.append(el('h3',item.name||MAP_POINT_CLASSES[item.class]||'Место'));const actions=el('div');actions.className='map-point-actions';const walk=el('button','Идти пешком'),horse=el('button','На лошади'),favorite=el('button',WorldSystem.isFavorite(state,item)?'★ В избранном':'☆ В избранное');const locked=['travelling','event','stopped','camp'].includes(state.world?.travel?.status);walk.disabled=locked;horse.disabled=locked;walk.onclick=()=>onTravel(item,'walk');horse.onclick=()=>onTravel(item,'horse');favorite.onclick=()=>onFavorite(item,favorite);actions.append(walk,horse,favorite);box.append(top,el('p',pointDescription(item)),actions);if(item.class==='location'&&item.map){const enter=el('button','Открыть карту локации');enter.className='map-point-enter';enter.onclick=()=>onTravel(item,'enter');box.append(enter)}return box}
