import {W,CL,ARMORS,CLASS_POOL,GRID,DEFAULT_BATTLE_CFG,mkbody} from '../alpha14p/data/constants.js';import {GameRNG,pick} from '../alpha14p/core/rng.js';
let cfg=structuredClone(DEFAULT_BATTLE_CFG),units=[],terrain={};
const $=id=>document.getElementById(id);
function gear(cls){if(cls==='guardian')return{w:pick(['sword','axe']),w2:null,shield:55};if(cls==='berserker')return{w:pick(['greatsword','greataxe']),w2:null,shield:0};if(['priest','firemage','wizard'].includes(cls))return{w:pick(['staff','wand']),w2:null,shield:0};if(cls==='archer')return{w:'bow',w2:'dagger',shield:0};if(cls==='crossbowman')return{w:'crossbow',w2:'dagger',shield:0};if(cls==='assassin')return{w:'dagger',w2:'dagger',shield:0};if(cls==='rogue')return{w:'throwknife',w2:'dagger',shield:0};return{w:'sword',w2:null,shield:0}}
function make(id,name,team,q,r,cls){let g=gear(cls),ak=pick(['light','medium','heavy']),ar=ARMORS[ak],magic=['priest','firemage','wizard'].includes(cls);return{id,name,team,q,r,cls,w:g.w,w2:g.w2,shield:g.shield,maxShield:g.shield,armorKind:ak,armorName:ar.n,armCover:ar.arm,legCover:ar.leg,body:mkbody(),hp:90,maxHp:90,bleed:0,armorHead:ar.head,maxArmorHead:ar.head,armorBody:ar.body,maxArmorBody:ar.body,ap:9,maxAp:9,st:100,mana:magic?80:0,maxMana:magic?80:0,skill:63,def:6,alive:true,bandages:1,loaded:false,guarding:false,poison:0,shock:0,stun:0,buffs:{stone:0,rage:0}}}
const hd=(q1,r1,q2,r2)=>{const x1=q1,z1=r1-(q1-(q1&1))/2,y1=-x1-z1,x2=q2,z2=r2-(q2-(q2&1))/2,y2=-x2-z2;return(Math.abs(x1-x2)+Math.abs(y1-y2)+Math.abs(z1-z2))/2};
function genTerrain(){terrain={};let density={open:.04,sparse:.11,normal:.18,dense:.28}[cfg.terrain]??.18,safe=[[1,4],[1,5],[1,6],[12,2],[12,3],[12,4],[12,5],[12,6],[11,7]];for(let q=0;q<GRID.C;q++)for(let r=0;r<GRID.R;r++){if(safe.some(p=>hd(q,r,p[0],p[1])<=1))continue;if(GameRNG.random()<density){let x=GameRNG.random();terrain[q+','+r]=x<.34?'rock':x<.68?'tree':'bush'}}}
function fill(){let o=CLASS_POOL.map(c=>'<option value="'+c+'">'+CL[c].n+'</option>').join('');['a0','a1','a2'].forEach((id,i)=>{$(id).innerHTML=o;$(id).value=cfg.allies[i]})}fill();
$('random').onclick=()=>['a0','a1','a2'].forEach(id=>$(id).value=pick(CLASS_POOL));
$('start').onclick=()=>{cfg.allies=['a0','a1','a2'].map(id=>$(id).value);cfg.enemies=Math.max(1,Math.min(6,+$('enemies').value||3));cfg.terrain=$('terrain').value;let ap=[[1,4],[1,5],[1,6]],ep=[[12,2],[12,3],[12,4],[12,5],[12,6],[11,7]];units=[];for(let i=0;i<3;i++)units.push(make('a'+i,i?'Союзник '+(i+1):'ГГ','ally',...ap[i],cfg.allies[i]));for(let i=0;i<cfg.enemies;i++)units.push(make('e'+i,'Враг '+(i+1),'enemy',...ep[i],pick(CLASS_POOL)));genTerrain();render();$('setup').classList.add('hidden');$('battle').classList.remove('hidden');$('hud').classList.remove('hidden')};
function render(){let by=new Map(units.map(u=>[u.q+','+u.r,u]));$('grid').replaceChildren();for(let r=0;r<GRID.R;r++)for(let q=0;q<GRID.C;q++){let d=document.createElement('div'),u=by.get(q+','+r),t=terrain[q+','+r];d.className='hex '+(t||'')+(u?' '+u.team:'');d.textContent=u?(u.team==='ally'?'С':'В')+(Number(u.id.slice(1))+1):(t==='rock'?'К':t==='tree'?'Д':t==='bush'?'Кст':'');$('grid').append(d)}$('round').textContent='Раунд 1 · '+units.length+' бойцов · '+cfg.terrain;$('summary').innerHTML=units.map(u=>'<div class="card"><b>'+u.name+'</b><br>'+CL[u.cls].n+'<br>'+W[u.w].n+(u.w2?' + '+W[u.w2].n:'')+'<br>'+u.armorName+'<br>HP '+u.hp+' · AP '+u.ap+'</div>').join('')}
$('back').onclick=()=>{$('setup').classList.remove('hidden');$('battle').classList.add('hidden');$('hud').classList.add('hidden')};
