import {W,CL,ARMORS,PD,CLASS_POOL,GRID,DEFAULT_BATTLE_CFG,mkbody} from '../alpha14p/data/constants.js';import {GameRNG,pick} from '../alpha14p/core/rng.js';
const TEST_POOL=['guardian','archer','berserker'];
let cfg=structuredClone(DEFAULT_BATTLE_CFG),units=[],terrain={},order=[],idx=0,round=1,over=false,auto=false,combatLog=[];
const log=s=>{combatLog.unshift('R'+round+' · '+s);if(combatLog.length>80)combatLog.length=80};
const $=id=>document.getElementById(id);
function gear(cls){if(cls==='guardian')return{w:pick(['sword','axe']),w2:null,shield:55};if(cls==='berserker')return{w:pick(['greatsword','greataxe']),w2:null,shield:0};if(['priest','firemage','wizard'].includes(cls))return{w:pick(['staff','wand']),w2:null,shield:0};if(cls==='archer')return{w:'bow',w2:'dagger',shield:0};if(cls==='crossbowman')return{w:'crossbow',w2:'dagger',shield:0};if(cls==='assassin')return{w:'dagger',w2:'dagger',shield:0};if(cls==='rogue')return{w:'throwknife',w2:'dagger',shield:0};return{w:'sword',w2:null,shield:0}}
function make(id,name,team,q,r,cls){let g=gear(cls),ak=pick(['light','medium','heavy']),ar=ARMORS[ak],magic=['priest','firemage','wizard'].includes(cls);return{id,name,team,q,r,cls,w:g.w,w2:g.w2,shield:g.shield,maxShield:g.shield,armorKind:ak,armorName:ar.n,armCover:ar.arm,legCover:ar.leg,body:mkbody(),hp:90,maxHp:90,bleed:0,armorHead:ar.head,maxArmorHead:ar.head,armorBody:ar.body,maxArmorBody:ar.body,ap:9,maxAp:9,st:100,mana:magic?80:0,maxMana:magic?80:0,skill:63,def:6,alive:true,bandages:1,loaded:false,guarding:false,poison:0,shock:0,stun:0,buffs:{stone:0,rage:0}}}
const hd=(q1,r1,q2,r2)=>{const x1=q1,z1=r1-(q1-(q1&1))/2,y1=-x1-z1,x2=q2,z2=r2-(q2-(q2&1))/2,y2=-x2-z2;return(Math.abs(x1-x2)+Math.abs(y1-y2)+Math.abs(z1-z2))/2};
function genTerrain(){terrain={};let density={open:.04,sparse:.11,normal:.18,dense:.28}[cfg.terrain]??.18,safe=[[1,4],[1,5],[1,6],[12,2],[12,3],[12,4],[12,5],[12,6],[11,7]];for(let q=0;q<GRID.C;q++)for(let r=0;r<GRID.R;r++){if(safe.some(p=>hd(q,r,p[0],p[1])<=1))continue;if(GameRNG.random()<density){let x=GameRNG.random();terrain[q+','+r]=x<.34?'rock':x<.68?'tree':'bush'}}}
function fill(){let o=TEST_POOL.map(c=>'<option value="'+c+'">'+CL[c].n+'</option>').join('');['a0','a1','a2'].forEach((id,i)=>{$(id).innerHTML=o;$(id).value=cfg.allies[i]})}fill();
$('random').onclick=()=>['a0','a1','a2'].forEach(id=>$(id).value=pick(TEST_POOL));
$('start').onclick=()=>{cfg.allies=['a0','a1','a2'].map(id=>$(id).value);cfg.enemies=Math.max(1,Math.min(6,+$('enemies').value||3));cfg.terrain=$('terrain').value;let ap=[[1,4],[1,5],[1,6]],ep=[[12,2],[12,3],[12,4],[12,5],[12,6],[11,7]];units=[];for(let i=0;i<3;i++)units.push(make('a'+i,i?'Союзник '+(i+1):'ГГ','ally',...ap[i],cfg.allies[i]));for(let i=0;i<cfg.enemies;i++)units.push(make('e'+i,'Враг '+(i+1),'enemy',...ep[i],pick(TEST_POOL)));order=[...units];idx=0;round=1;over=false;auto=false;combatLog=[];genTerrain();render();$('setup').classList.add('hidden');$('battle').classList.remove('hidden');$('hud').classList.remove('hidden')};
function render(){let by=new Map(units.filter(u=>u.alive).map(u=>[u.q+','+u.r,u]));$('grid').replaceChildren();for(let r=0;r<GRID.R;r++)for(let q=0;q<GRID.C;q++){let d=document.createElement('div'),u=by.get(q+','+r),t=terrain[q+','+r];d.className='hex '+(t||'')+(u?' '+u.team:'');d.dataset.q=q;d.dataset.r=r;d.style.left='calc(50% + '+((q-(GRID.C-1)/2)*36)+'px - 24px)';d.style.top='calc(50% + '+((r-(GRID.R-1)/2)*55.426+(q&1)*27.713)+'px - 27.713px)';d.textContent=u?(u.team==='ally'?'🔵 ':'🔴 ')+(Number(u.id.slice(1))+1):(t==='rock'?'К':t==='tree'?'Д':t==='bush'?'Кст':'');$('grid').append(d)}$('round').textContent='Раунд 1 · '+units.length+' бойцов · '+cfg.terrain;$('summary').innerHTML=units.map(u=>'<div class="card"><b>'+u.name+'</b><br>'+CL[u.cls].n+'<br>'+W[u.w].n+(u.w2?' + '+W[u.w2].n:'')+'<br>'+u.armorName+'<br>HP '+u.hp+' · AP '+u.ap+' · ST '+u.st+'<br>Щит '+u.shield+'/'+u.maxShield+' · Броня '+u.armorHead+'/'+u.armorBody+'<br>Кровотечение '+u.bleed+(u.alive?'':' · ВЫБЫЛ')+'</div>').join('')}
$('back').onclick=()=>{$('setup').classList.remove('hidden');$('battle').classList.add('hidden');$('hud').classList.add('hidden')};

const dirs=(q)=>(q&1)?[[1,0],[1,1],[0,1],[-1,1],[-1,0],[0,-1]]:[[1,-1],[1,0],[0,1],[-1,0],[-1,-1],[0,-1]];
const neigh=(q,r)=>dirs(q).map(d=>[q+d[0],r+d[1]]).filter(p=>p[0]>=0&&p[0]<GRID.C&&p[1]>=0&&p[1]<GRID.R);
const at=(q,r)=>units.find(u=>u.alive&&u.q===q&&u.r===r);
const blocked=(q,r)=>['rock','tree'].includes(terrain[q+','+r]);
const dist=(a,b)=>hd(a.q,a.r,b.q,b.r);
const activeWeapon=(a,t)=>(a.cls==='archer'&&dist(a,t)<=1&&a.w2)?a.w2:a.w;
const moveCost=a=>{let legs=['lleg','rleg'].map(k=>a.body[k]),crip=legs.filter(x=>x.hp<=0).length;return crip?{ap:4,st:18}:{ap:a.st<25?3:2,st:8}};
const partKeys=['head','torso','larm','rarm','lleg','rleg'];
const rndPart=()=>{let x=GameRNG.random()*100;return x<10?'head':x<50?'torso':x<62?'larm':x<74?'rarm':x<87?'lleg':'rleg'};
function coverPenalty(a,t){let pen=0,steps=Math.max(1,Math.ceil(dist(a,t)));for(let i=1;i<steps;i++){let q=Math.round(a.q+(t.q-a.q)*i/steps),r=Math.round(a.r+(t.r-a.r)*i/steps),z=terrain[q+','+r];if(z==='tree')pen+=25;else if(z==='bush')pen+=7;else if(z==='rock')pen+=35}if(terrain[t.q+','+t.r]==='bush')pen+=10;return Math.min(75,pen)}
function chance(a,t,p=null,wk=null){let w=W[wk||activeWeapon(a,t)],pen=w.type==='bow'?Math.max(0,dist(a,t)-2)*8:0,fat=a.st<25?20:a.st<50?8:0,cov=w.type==='bow'?coverPenalty(a,t):0;return Math.max(5,Math.min(95,a.skill+w.acc-t.def-pen-fat-cov+(p?PD[p].mod:0)))}
function oneHit(a,t,p,wk,m=1){let w=W[wk],fat=a.st<25?.7:a.st<50?.88:1,raw=Math.max(1,Math.round((w.min+GameRNG.random()*(w.max-w.min))*fat*m));if(t.shield>0&&GameRNG.random()<(w.type==='bow'?.82:.65)){let sd=Math.max(1,Math.round(raw*w.sd));t.shield=Math.max(0,t.shield-sd);log(a.name+' → '+t.name+': щит −'+sd);return}let slot=p==='head'?'armorHead':p==='torso'||p.includes('arm')||p.includes('leg')?'armorBody':null,cover=p==='head'?1:p==='torso'?1:p.includes('arm')?t.armCover:t.legCover,bodyD=raw;if(slot&&t[slot]>0&&GameRNG.random()<cover){let max='max'+slot[0].toUpperCase()+slot.slice(1),ratio=t[slot]/t[max],pen=Math.min(.7,(w.pen||.1)+(1-ratio)*.45);bodyD=Math.max(1,Math.round(raw*pen));t[slot]=Math.max(0,t[slot]-Math.max(1,Math.round(raw*(w.ad||.5))))}let before=t.body[p].hp;t.body[p].hp=Math.max(0,before-bodyD);t.hp=Math.max(0,t.hp-bodyD);if(before>0&&t.body[p].hp<=0&&['larm','rarm','lleg','rleg'].includes(p))t.bleed=Math.min(12,(t.bleed||0)+2);if(t.hp<=0||t.body.head.hp<=0||t.body.torso.hp<=0)t.alive=false;log(a.name+' → '+t.name+': '+PD[p].n+' −'+bodyD+(t.alive?'':' · ВЫБЫЛ'))}
function attack(a,t,p=null){let wk=activeWeapon(a,t),w=W[wk],cost=p?5:w.ap;if(a.ap<cost||dist(a,t)>w.r)return false;a.ap-=cost;a.st=Math.max(0,a.st-(p?18:14));let ch=chance(a,t,p,wk);if(GameRNG.random()*100<=ch)oneHit(a,t,p||rndPart(),wk,p?PD[p].m:1);else log(a.name+' → '+t.name+': ПРОМАХ ('+Math.round(ch)+'%)');checkEnd();return true}
function checkEnd(){let A=units.some(u=>u.alive&&u.team==='ally'),E=units.some(u=>u.alive&&u.team==='enemy');over=!A||!E;if(over){$('round').textContent=(A?'Победа':'Поражение')+' · раунд '+round}return over}
function nextTurn(){if(over)return;do{idx++;if(idx>=order.length){idx=0;round++}}while(!order[idx].alive);let c=order[idx];if(c.bleed){log(c.name+': кровотечение −'+c.bleed);c.hp=Math.max(0,c.hp-c.bleed);if(c.hp<=0)c.alive=false;if(checkEnd())return nextRender()}c.ap=9;c.st=Math.min(100,c.st+12);nextRender();if(auto||c.id!=='a0')setTimeout(aiTurn,60)}
function aiTurn(){if(over)return;let a=order[idx];if(!a.alive)return nextTurn();let foes=units.filter(x=>x.alive&&x.team!==a.team).sort((x,y)=>dist(a,x)-dist(a,y)),t=foes[0];if(!t)return;let acted=false,wk=activeWeapon(a,t),w=W[wk];if(dist(a,t)<=w.r&&a.ap>=w.ap)acted=attack(a,t);else{let mc=moveCost(a),before=dist(a,t),o=neigh(a.q,a.r).filter(p=>!at(...p)&&!blocked(...p)&&hd(p[0],p[1],t.q,t.r)<before).sort((x,y)=>hd(x[0],x[1],t.q,t.r)-hd(y[0],y[1],t.q,t.r))[0];if(o&&a.ap>=mc.ap){a.q=o[0];a.r=o[1];a.ap-=mc.ap;a.st=Math.max(0,a.st-mc.st);acted=true}}nextRender();if(!acted)return setTimeout(nextTurn,60);setTimeout(()=>{if(over)return;let target=units.filter(x=>x.alive&&x.team!==a.team).sort((x,y)=>dist(a,x)-dist(a,y))[0];if(!target)return;let aw=W[activeWeapon(a,target)],mc=moveCost(a);let canAttack=dist(a,target)<=aw.r&&a.ap>=aw.ap,canMove=a.ap>=mc.ap&&neigh(a.q,a.r).some(p=>!at(...p)&&!blocked(...p)&&hd(p[0],p[1],target.q,target.r)<dist(a,target));if(canAttack||canMove)aiTurn();else nextTurn()},60)}
function nextRender(){render();$('round').textContent=(over?$('round').textContent:'Раунд '+round+' · ход '+(order[idx]?.name||''));let l=$('combatLog');if(l)l.textContent=combatLog.slice(0,18).join('\n');}
function simulateBatch(n=100){
 let wins={ally:0,enemy:0,draw:0},rounds=0,maxRounds=0,oldAuto=auto;
 const snap={cfg:structuredClone(cfg),units:structuredClone(units),terrain:structuredClone(terrain),order:structuredClone(order),idx,round,over,combatLog:[...combatLog]};
 for(let k=0;k<n;k++){
  let ap=[[1,4],[1,5],[1,6]],ep=[[12,2],[12,3],[12,4]],pool=TEST_POOL;
  units=[];for(let i=0;i<3;i++)units.push(make('a'+i,i?'Союзник '+(i+1):'ГГ','ally',...ap[i],pick(pool)));
  for(let i=0;i<3;i++)units.push(make('e'+i,'Враг '+(i+1),'enemy',...ep[i],pick(pool)));
  order=[...units];idx=0;round=1;over=false;combatLog=[];genTerrain();
  let guard=0;
  while(!over&&round<=250&&guard++<6000){
   let a=order[idx];
   if(!a.alive){nextTurnSync();continue}
   let foes=units.filter(x=>x.alive&&x.team!==a.team).sort((x,y)=>dist(a,x)-dist(a,y)),t=foes[0];
   if(!t){checkEnd();break}
   let wk=activeWeapon(a,t),w=W[wk],acted=false;
   if(dist(a,t)<=w.r&&a.ap>=w.ap)acted=attack(a,t);
   else{let mc=moveCost(a),before=dist(a,t),o=neigh(a.q,a.r).filter(p=>!at(...p)&&!blocked(...p)&&hd(p[0],p[1],t.q,t.r)<before).sort((x,y)=>hd(x[0],x[1],t.q,t.r)-hd(y[0],y[1],t.q,t.r))[0];if(o&&a.ap>=mc.ap){a.q=o[0];a.r=o[1];a.ap-=mc.ap;a.st=Math.max(0,a.st-mc.st);acted=true}}
   if(!acted||a.ap<Math.min(moveCost(a).ap,W[activeWeapon(a,t)]?.ap||99))nextTurnSync()
  }
  let A=units.some(u=>u.alive&&u.team==='ally'),E=units.some(u=>u.alive&&u.team==='enemy');wins[A&&!E?'ally':E&&!A?'enemy':'draw']++;rounds+=round;maxRounds=Math.max(maxRounds,round)
 }
 cfg=snap.cfg;units=snap.units;terrain=snap.terrain;order=snap.order;idx=snap.idx;round=snap.round;over=snap.over;combatLog=snap.combatLog;auto=oldAuto;nextRender();
 let report=['EIRDAN 0.15 · BATCH DIAGNOSTIC','BUILD: '+(window.EIRDAN_BUILD||'unknown'),'BATTLES: '+n,'SEED CALLS: '+GameRNG.calls,'','RESULTS','Allies: '+wins.ally,'Enemies: '+wins.enemy,'Draws/timeouts: '+wins.draw,'Average rounds: '+(rounds/n).toFixed(1),'Max rounds: '+maxRounds,'','NOTE: balance values unchanged.'].join('\n');let a=document.createElement('a');a.href='data:text/plain;charset=utf-8,'+encodeURIComponent('\uFEFF'+report);a.download='Eirdan_batch_diagnostic_'+Date.now()+'.txt';a.target='_blank';a.rel='noopener';document.body.append(a);a.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window}));a.remove();alert('Симуляция ×'+n+' завершена.\nTXT отправлен в загрузки браузера.\nСоюзники: '+wins.ally+' · Враги: '+wins.enemy+' · Ничьи: '+wins.draw)
}
function nextTurnSync(){if(over)return;do{idx++;if(idx>=order.length){idx=0;round++}}while(!order[idx].alive);let c=order[idx];if(c.bleed){c.hp=Math.max(0,c.hp-c.bleed);if(c.hp<=0)c.alive=false;if(checkEnd())return}c.ap=9;c.st=Math.min(100,c.st+12)}
$('sim100').onclick=()=>simulateBatch(100);
const oldStart=$('start').onclick;$('start').onclick=()=>{oldStart();let lg=document.createElement('div');lg.id='combatLog';lg.style='margin-top:10px;max-height:180px;overflow:auto;font-size:12px;line-height:1.5;white-space:pre-line';$('hud').append(lg);let b=document.createElement('button');b.id='auto';b.textContent='Автобой';b.onclick=()=>{auto=true;if(order[idx].id==='a0')aiTurn()};$('hud').querySelector('.actions').append(b);let e=document.createElement('button');e.id='endTurn';e.textContent='Конец хода';e.onclick=()=>{if(!auto&&order[idx]?.id==='a0')nextTurn()};$('hud').querySelector('.actions').append(e);nextRender()};
$('grid').onclick=e=>{let cells=[...$('grid').children],i=cells.indexOf(e.target.closest('.hex'));if(i<0||over||auto||order[idx]?.id!=='a0')return;let h=e.target.closest('.hex'),q=+h.dataset.q,r=+h.dataset.r,a=order[idx],u=at(q,r);if(u&&u.team!==a.team){attack(a,u);nextRender();return}let mc=moveCost(a);if(!u&&!blocked(q,r)&&a.ap>=mc.ap&&neigh(a.q,a.r).some(p=>p[0]===q&&p[1]===r)){a.q=q;a.r=r;a.ap-=mc.ap;a.st=Math.max(0,a.st-mc.st);nextRender()}};
