// ============================================================================
// WORLD UI ADAPTER
// Composes world/region/location presentation and forwards actions to systems.
// Gameplay rules, travel simulation and editor internals belong to their owners.
// ============================================================================
import {WORLD_DATA} from '../data/world.js';
import {WorldSystem} from '../systems/world/world.js';
import {MapViewSystem} from '../map/view-state.js';
import {CENTRAL_LANDS} from '../data/regions/central-lands.js';
import {VELIGRAD} from '../data/locations/veligrad.js';
import {VELIGRAD_NAVIGATION} from '../data/locations/veligrad-navigation.js';
import {LocationTravelSystem} from '../systems/travel/location-travel.js';
import {LocationEntrySystem} from '../systems/travel/entry.js';
import {CampSystem} from '../systems/travel/camp.js';
import {SimulationSystem} from '../systems/simulation.js';
import {JourneySystem} from '../systems/travel/journey.js';
import {CENTRAL_LANDS_ROADS} from '../data/regions/central-lands-roads.js';
import {TravelSystem} from '../systems/travel/travel.js';
import {loadEditableRoads} from '../tools/map-editor/road-editor.js';
import {createMapEditorSession} from '../tools/map-editor/session.js';
import {loadTerrainZones} from '../tools/map-editor/terrain-store.js';
import {mapMetrics} from '../data/map-metrics.js';
import {mapPoint} from './map-gestures.js';
import {createPoiAuthoring} from '../tools/map-editor/poi-authoring.js';
import {loadPoi,savePoi} from '../map/poi-store.js';
import {el} from './map-ui.js';
import {MAP_POINT_CLASSES as CLASSES,MAP_POINT_TYPES as TYPES,pointIcon,legendFor,actionPanel} from './map-points.js';

function clampPin(pin,frame,item){const x=item?.x??.5,y=item?.y??.5;let tx='-50%',ty='-50%';if(x<.14)tx='0%';else if(x>.86)tx='-100%';if(y<.08)ty='0%';else if(y>.92)ty='-100%';pin.style.transform=`translate(${tx},${ty})`}


export const WorldUI={
 ready:true,
 mount(root,state,onChange,onAudioContext=()=>{}){
  let pixels=null,mw=0,mh=0,indexToId={},regionCenters={};
  for(const [id,r] of Object.entries(WORLD_DATA.regions))indexToId[r.index]=id;
  const current=WorldSystem.ensure(state);
  if(current.regionId&&!WORLD_DATA.regions[current.regionId])current.regionId=null;
  const view=MapViewSystem.ensure(state);let mode=view.level;
  let cleanup=()=>{};

  // --------------------------------------------------------------------------
  // WORLD MAP VIEW — renders global regions/fog and forwards region selection.
  // --------------------------------------------------------------------------
  function renderWorld(){
   cleanup();onAudioContext('world');root.replaceChildren();
   const physicalRegion=()=>state.world?.position?.regionId||current.regionId;const statusText=()=>physicalRegion()?'Отряд находится в регионе: '+(WORLD_DATA.regions[physicalRegion()]?.name||physicalRegion()):'Местоположение отряда не определено';
   const head=el('div');head.className='world-head';const fogToggle=el('button','Туман: вкл');fogToggle.className='world-fog-toggle';head.append(el('h2','Карта мира'),fogToggle);let fogEnabled=true;
   const status=el('p',statusText());status.className='world-region-status';head.append(status);root.append(head);
   const frame=el('div');frame.className='world-map-frame';
   const img=el('img');img.className='world-map-image';img.src=WORLD_DATA.map.asset;img.alt='Карта мира Эйрдан';frame.append(img);
   const shade=el('canvas');shade.className='world-region-shade';frame.append(shade);const regionLabel=el('div');regionLabel.className='world-selected-region';frame.append(regionLabel);root.append(frame);
   function draw(){regionLabel.textContent=view.regionId?WORLD_DATA.regions[view.regionId]?.name||'':'';const center=view.regionId?regionCenters[WORLD_DATA.regions[view.regionId]?.index]:null;if(center){regionLabel.style.left=(center.x/mw*100)+'%';regionLabel.style.top=(center.y/mh*100)+'%'}if(!pixels)return;shade.width=mw;shade.height=mh;const ctx=shade.getContext('2d'),out=ctx.createImageData(mw,mh);const selected=view.regionId?WORLD_DATA.regions[view.regionId]?.index:0;for(let p=0,i=0;p<pixels.length;p++,i+=4){const idx=pixels[p],id=indexToId[idx];if(fogEnabled&&idx>0&&idx!==selected&&!WorldSystem.isRegionAvailable(state,id)){out.data[i]=18;out.data[i+1]=24;out.data[i+2]=23;out.data[i+3]=218}else if(idx>0&&idx!==selected){out.data[i+3]=58}}ctx.putImageData(out,0,0)}
   const mask=new Image();mask.onload=()=>{mw=mask.naturalWidth;mh=mask.naturalHeight;const c=document.createElement('canvas');c.width=mw;c.height=mh;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(mask,0,0);const d=x.getImageData(0,0,mw,mh).data;pixels=new Uint8Array(mw*mh);const sums={};for(let p=0,i=0;p<pixels.length;p++,i+=4){const idx=d[i];pixels[p]=idx;if(idx>0){const q=sums[idx]||(sums[idx]={x:0,y:0,n:0});q.x+=p%mw;q.y+=Math.floor(p/mw);q.n++}}regionCenters={};for(const [idx,q] of Object.entries(sums))regionCenters[idx]={x:q.x/q.n,y:q.y/q.n};draw()};mask.src=WORLD_DATA.map.mask;
   const regionActions=el('div');regionActions.className='world-region-actions hidden';root.append(regionActions);function clearRegionSelection(){view.regionId=null;regionActions.classList.add('hidden');regionActions.replaceChildren();regionLabel.classList.add('hidden');draw()}function selectRegion(id){const region=WORLD_DATA.regions[id];if(!region){clearRegionSelection();return false}view.regionId=id;regionLabel.classList.remove('hidden');draw();const display=region.politicalName||region.name;const card=el('section');card.className='map-point-card';card.append(el('h3',display));if(region.geographicName||region.name)card.append(el('p','География: '+(region.geographicName||region.name)));card.append(el('p',region.summary||'Краткая информация о регионе пока не задана.'));const info=el('p',(region.population?'Население: '+region.population:'Население: данные не заданы'));info.className='quiet';card.append(info);const actions=el('div');actions.className='map-point-actions';const open=el('button','Открыть регион'),cancel=el('button','Отменить выбор'),description=el('button','Описание');open.disabled=!region.map;open.onclick=()=>{MapViewSystem.region(state,id);mode='region';onChange?.(state);renderRegion(id)};cancel.onclick=clearRegionSelection;description.onclick=()=>{const detail=el('div');detail.className='region-description';detail.append(el('p',region.description||'Подробное описание региона пока не заполнено.'),el('p',region.populationDetails||'Сведения о населении пока не заполнены.'));card.append(detail);description.disabled=true};actions.append(open,cancel,description);card.append(actions);regionActions.replaceChildren(card);regionActions.classList.remove('hidden')}fogToggle.onclick=()=>{fogEnabled=!fogEnabled;fogToggle.textContent='Туман: '+(fogEnabled?'вкл':'выкл');draw()};frame.onclick=e=>{if(!pixels)return;const r=frame.getBoundingClientRect(),x=Math.max(0,Math.min(mw-1,Math.floor((e.clientX-r.left)/r.width*mw))),y=Math.max(0,Math.min(mh-1,Math.floor((e.clientY-r.top)/r.height*mh))),id=indexToId[pixels[y*mw+x]];if(!id||!WORLD_DATA.regions[id]){clearRegionSelection();return}selectRegion(id)};
   cleanup=()=>{frame.onclick=null};
  }

  // --------------------------------------------------------------------------
  // REGION VIEW — renders regional POIs/travel state; systems own game rules.
  // Map Editor is composed through tools/map-editor public interfaces.
  // --------------------------------------------------------------------------
  function renderRegion(regionId=view.regionId||current.regionId||'forest'){
   cleanup();onAudioContext('world');root.replaceChildren();
   const region=WORLD_DATA.regions[regionId];
   if(!region?.map){const head=el('div');head.className='region-head';const back=el('button','← Мир');back.className='region-back';head.append(back,el('h2',region?.name||'Регион'));root.append(head,el('p','Карта этого региона пока не добавлена. Предпросмотр не изменяет положение отряда.'));back.onclick=()=>{MapViewSystem.world(state);mode='world';onChange?.(state);renderWorld()};cleanup=()=>{back.onclick=null};return}
   
   const head=el('div');head.className='region-head';
   const back=el('button','← Мир');back.className='region-back';
   const title=el('div');title.append(el('h2',region.name),el('p','Карта региона'));
   const edit=el('button','Редактор');edit.className='region-edit-toggle';
   head.append(back,title,edit);root.append(head);
   const frame=el('div');frame.className='region-map-frame';
   const img=el('img');img.className='region-map-image';img.src=region.map.asset;img.alt=region.name;frame.append(img);
   const layer=el('div');layer.className='region-poi-layer';frame.append(layer);
   const party=el('div');party.className='party-marker';party.title='Ваш отряд';frame.append(party);const freeTarget=el('div');freeTarget.className='free-travel-target hidden';frame.append(freeTarget);root.append(frame);
   const actionHost=el('div');actionHost.className='map-point-action-host';root.append(actionHost);
   let editing=false,items=loadPoi('forest'),roads=loadEditableRoads('forest',CENTRAL_LANDS_ROADS),terrainZones=loadTerrainZones('region:forest',[]);roads.metrics={...mapMetrics('region','forest')};roads.regionId='forest';let editorMode='poi',editorLabels=false,drag=null,editorSelected=null,selected=current.placeId||current.districtId||current.locationId||null,travelTimer=null,lastTravelAt=0;const legendHost=el('div');legendHost.className='map-legend-host';frame.append(legendHost);
   const editorSession=createMapEditorSession({root,frame,editButton:edit,kind:'region',panelOptions:{poiOptions:[['location-map','Локация с картой'],['location','Локация без карты'],['place','Конечное место']],poiInitial:'location-map',poiPlaceholder:'Название локации',hintText:'Выберите функциональный класс и нажмите на карту. Метку можно перетаскивать.',clearLabel:'Сбросить к штатным'},roadMapId:'forest',terrainMapId:'region:forest',roads,zones:terrainZones,getPois:()=>items,getMode:()=>editorMode,setMode:value=>{editorMode=value;drag=null},getEditing:()=>editing,setEditing:value=>{editing=value},onPaint:paint,onModeChange:syncEditorTools,onRoadsChange:r=>{roads=r},onZonesChange:z=>{terrainZones=z},onRoadSelection:(s,{panel,roadEditor})=>{panel.bindRoadPoi.disabled=!s.nodeId;const np=s.node?roadEditor.nearestPoi(s.node.x,s.node.y,.08):null;panel.bindRoadPoi.textContent=np?'Привязать к «'+np.name+'»':'Привязать узел к метке';panel.road.selection.textContent=s.nodeId?'Выбран узел: '+s.nodeId:s.edge?'Выбран участок: '+s.edge[0]+' → '+s.edge[1]:'Ничего не выбрано'},clearTerrainMessage:'Удалить все зоны местности региона?',clearRoadsMessage:'Удалить ВСЕ дорожные узлы и участки региона?'});
   const {panel:editorPanel,roadEditor}=editorSession;const {hint,toggleLabels,bindRoadPoi,clearOptionalPoi,poiSelection,removePoi}=editorPanel;removePoi.onclick=()=>{const item=items.find(p=>p.id===editorSelected);if(item&&poiAuthoring.remove(item)){editorSelected=null;poiSelection.textContent='Метка не выбрана';removePoi.disabled=true}};
   const poiAuthoring=createPoiAuthoring({frame,panel:editorPanel,getItems:()=>items,setItems:value=>{items=value},persist:()=>persist(),getEditing:()=>editing,getMode:()=>editorMode,getDrag:()=>drag,setDrag:value=>{drag=value},createPoint:({choice,label,x,y,slug})=>{const cls=choice==='location-map'?'location':choice,resolved=label||(choice==='location-map'?'Локация с картой':choice==='location'?'Локация':'Место');return{id:'forest-'+slug(resolved)+'-'+Date.now().toString(36),name:resolved,class:cls,type:cls,...(choice==='location-map'?{map:null}:{}),x,y}},exportFile:'region-central-lands-poi.json',exportPayload:()=>({region:'forest',map:region.map.asset,points:items}),resetConfirm:'Сбросить локальные изменения и вернуть штатные метки Центральных земель?',resetItems:()=>CENTRAL_LANDS.points.map(p=>({...p}))});
   toggleLabels.onclick=()=>{editorLabels=!editorLabels;toggleLabels.textContent=editorLabels?'Свернуть названия':'Развернуть названия';paint()};clearOptionalPoi.onclick=()=>{if(confirm('Удалить все обычные метки, сохранив функциональные точки и локации с картами?')){items=items.filter(p=>p.map||p.class==='transition'||p.type==='transition');persist()}};bindRoadPoi.onclick=()=>{const sel=roadEditor.selection().node;if(!sel)return;const p=roadEditor.nearestPoi(sel.x,sel.y,.08);if(!p){alert('Рядом с выбранным узлом нет метки.');return}if(confirm('Привязать выбранный узел к месту «'+p.name+'»?'))roadEditor.bindPoi(p.id,sel.id)};
   function partyPoint(){const t=TravelSystem.ensure(state);if(t.regionId==='forest'&&t.position&&['travelling','event','stopped','camp'].includes(t.status))return t.position;if(state.world?.position?.position)return state.world.position.position;const id=state.world?.position?.pointId||current.locationId||current.placeId||'veligrad';return items.find(p=>p.id===id)||CENTRAL_LANDS.points.find(p=>p.id===id)||CENTRAL_LANDS.points.find(p=>p.id==='veligrad')}
   function paintParty(){const p=partyPoint(),t=TravelSystem.ensure(state),active=['travelling','event','stopped','camp'].includes(t.status),startId=active?(t.fromId&&t.fromId!=='road-position'&&t.fromId!=='free-position'?t.fromId:null):null,targetId=active?t.toId:null;party.classList.toggle('hidden',!p);if(p){party.style.left=(p.x*100)+'%';party.style.top=(p.y*100)+'%'}for(const pin of layer.querySelectorAll('.region-poi')){const item=items.find(x=>x.id===pin.dataset.id);if(!item||!p)continue;const near=Math.hypot(item.x-p.x,item.y-p.y)<.045,isStart=item.id===startId,isTarget=item.id===targetId;pin.classList.toggle('party-near',near);pin.classList.toggle('route-start',isStart);pin.classList.toggle('route-target',isTarget);pin.classList.toggle('travel-label',near||isStart||isTarget)}}
   function paint(){
    layer.replaceChildren();legendHost.replaceChildren(legendFor(items,state,editing));
    for(const item of items){
     if(!editing&&!WorldSystem.isDiscovered(state,item))continue;
     const favorite=WorldSystem.isFavorite(state,item);const pin=el('button');pin.className='region-poi'+(((editing&&editorLabels)||editorSelected===item.id||selected===item.id||favorite)?' expanded':'');if(editing&&editorSelected===item.id)pin.classList.add('editor-selected');pin.dataset.id=item.id;pin.dataset.type=item.type;pin.dataset.class=item.class||'place';pin.style.left=(item.x*100)+'%';pin.style.top=(item.y*100)+'%';pin.title=item.name||TYPES[item.type];if(favorite)pin.classList.add('favorite');
     const dot=el('span',pointIcon(item));dot.className='point-symbol';const label=el('span',item.name||TYPES[item.type]);label.className='point-label';pin.append(dot,label);if(favorite){const star=el('span','★');star.className='point-favorite';pin.append(star)};layer.append(pin);clampPin(pin,frame,item);
     pin.onclick=e=>{e.stopPropagation();if(editing&&editorMode==='road')return;if(editing){editorSelected=item.id;poiSelection.textContent='Выбрана метка: '+item.name+' · ID: '+item.id;removePoi.disabled=false;paint();return}freeTarget.classList.add('hidden');selected=item.id;paint();showActions(item)};
     poiAuthoring.bindPin(pin,item);
    }
    paintParty();
   }
   function persist(){savePoi('forest',items);paint()}
   function routeStatus(t){let box=actionHost.querySelector('.travel-status');if(!box){box=el('section');box.className='travel-status';actionHost.append(box)}const p=TravelSystem.progress(state),pct=Math.round(p.ratio*100),km=n=>(n/1000).toFixed(n>=10000?1:2);box.replaceChildren(el('div','Путь: '+pct+'% · '+km(p.done)+' км / '+km(p.total)+' км · осталось '+km(p.left)+' км'));const bar=el('progress');bar.max=1;bar.value=p.ratio;box.append(bar);const actions=el('div');actions.className='travel-actions';const camp=el('button',t.status==='camp'?'Свернуть лагерь':'Разбить лагерь');camp.onclick=()=>{if(t.status==='camp'){SimulationSystem.stopSleep(state);CampSystem.remove(state);TravelSystem.resume(state,{roads,points:items,terrainZones});SimulationSystem.setMode(state,'travel')}else{TravelSystem.camp(state,{roads,points:items,terrainZones});CampSystem.create(state,{regionId:t.regionId,position:t.position});SimulationSystem.setFastForward(state,false);SimulationSystem.setMode(state,'world')}routeStatus(t);onChange?.(state)};const cancel=el('button','Отменить путь');cancel.onclick=()=>{TravelSystem.cancel(state,{roads,points:items,terrainZones});SimulationSystem.stopSleep(state);CampSystem.remove(state);SimulationSystem.setMode(state,'world');box.remove();paintParty();onChange?.(state)};actions.append(camp);if(t.status==='camp'){const sleep=el('button',SimulationSystem.ensure(state).sleep?'Спим…':'Спать 8 часов');sleep.disabled=!!SimulationSystem.ensure(state).sleep;sleep.onclick=()=>{SimulationSystem.startSleep(state,{hours:8});SimulationSystem.setFastForward(state,true);routeStatus(t);onChange?.(state)};actions.append(sleep)}actions.append(cancel);box.append(actions)}
   function startTravel(target,method){onAudioContext('travel');const active=TravelSystem.ensure(state);if(state.world?.position?.locationId==='veligrad'&&target.id&&target.id!=='veligrad'){const journey=JourneySystem.startExit(state,{location:VELIGRAD,locationNavigation:loadEditableRoads('location:veligrad',VELIGRAD_NAVIGATION),locationPoints:loadPoi('location:veligrad'),regionalRoads:roads,regionalPoints:items,targetId:target.id,method,terrainZones});if(!journey){const msg=el('p','Не удалось построить маршрут из Великграда к этой цели.');msg.className='quiet map-route-status';actionHost.append(msg);return}MapViewSystem.location(state,'forest','veligrad');view.locationId='veligrad';mode='location';onChange?.(state);renderLocation(VELIGRAD);return}if(['travelling','event','stopped','camp'].includes(active.status)){const msg=el('p','Сначала отмените текущий путь.');msg.className='quiet map-route-status';actionHost.append(msg);return}const anchored=state.world?.position?.pointId||null,from=anchored||current.locationId||current.placeId||'veligrad';if(anchored===target.id){WorldSystem.enterMapPoint(state,target);onChange?.(state);paint();return}const free=anchored?null:state.world?.position?.position||active.position||null,t=TravelSystem.start(state,{roads,points:items,fromId:from,toId:target.id||null,toPosition:target.id?null:{x:target.x,y:target.y},method,fromPosition:free,terrainZones});if(!t){const msg=el('p','К этой точке пока нет доступного маршрута.');msg.className='quiet map-route-status';actionHost.append(msg);return}state.world.camp=null;SimulationSystem.setMode(state,'travel');const old=actionHost.querySelector('.map-route-status');old?.remove();const msg=el('p',(method==='horse'?'Верхом':'Пешком')+': '+(t.distanceTotal/1000).toFixed(2)+' км');msg.className='quiet map-route-status';actionHost.append(msg);routeStatus(t);lastTravelAt=performance.now();if(!travelTimer)travelTimer=requestAnimationFrame(travelFrame);onChange?.(state);paintParty()}
   function travelFrame(now){travelTimer=null;const t=TravelSystem.ensure(state);if(!['travelling','event','stopped','camp'].includes(t.status))return;const dt=Math.min(.1,Math.max(0,(now-(lastTravelAt||now))/1000));lastTravelAt=now;if(t.status==='travelling'){const before=t.distanceDone||0;TravelSystem.tick(state,dt,roads,SimulationSystem.multiplier(state));if((t.distanceDone||0)>before)onChange?.(state);paintParty();routeStatus(t);if(t.status==='arrived'){const dest=items.find(p=>p.id===t.toId);const arrivalPortId=dest?.map?(t.toPortId||t.route?.toPortId||null):TravelSystem.arrive(state);if(state.world?.journey?.status==='region')JourneySystem.finish(state);freeTarget.classList.add('hidden');if(dest)WorldSystem.enterMapPoint(state,dest);else WorldSystem.leaveLocationForRegion(state);SimulationSystem.setMode(state,'world');onChange?.(state);paint();if(dest)showActions(dest);else actionHost.replaceChildren();return}}travelTimer=requestAnimationFrame(travelFrame)}
   function showActions(item){actionHost.replaceChildren(actionPanel(item,state,(p,method)=>{if(method==='preview'&&p.map){MapViewSystem.location(state,'forest',p.id);view.locationId=p.id;mode='location';onChange?.(state);renderLocation(p);return}if(method==='enter'&&p.map){const spawn=LocationEntrySystem.enter(state,{location:p,navigation:loadEditableRoads('location:'+p.id,p.id==='veligrad'?VELIGRAD_NAVIGATION:{nodes:[],edges:[],access:{}}),points:loadPoi('location:'+p.id)});if(!spawn)return;MapViewSystem.location(state,'forest',p.id);view.locationId=p.id;mode='location';onChange?.(state);renderLocation(p);return}startTravel(p,method)},(p,b)=>{const favorite=WorldSystem.toggleFavorite(state,p);b.textContent=favorite?'★ В избранном':'☆ В избранное';onChange?.(state);paint()}))}
   frame.onclick=e=>{if(e.target.closest('.region-poi'))return;const mp=mapPoint(frame,e.clientX,e.clientY);if(!editing){selected=null;WorldSystem.clearMapPoint(state);const target={x:mp.x,y:mp.y};freeTarget.style.left=(target.x*100)+'%';freeTarget.style.top=(target.y*100)+'%';freeTarget.classList.remove('hidden');const card=el('section');card.className='map-point-card free-travel-card';const anchors=items.filter(p=>['city','village','fort'].includes(p.type));const metrics=mapMetrics('region','forest')||{widthMeters:1,heightMeters:1};let nearest=null;for(const p of anchors){const dx=(target.x-p.x)*metrics.widthMeters,dy=(target.y-p.y)*metrics.heightMeters,d=Math.hypot(dx,dy);if(!nearest||d<nearest.d)nearest={p,d,dx,dy}}const direction=nearest?(Math.abs(nearest.dy)>Math.abs(nearest.dx)*1.8?(nearest.dy>0?'Южнее':'Севернее'):Math.abs(nearest.dx)>Math.abs(nearest.dy)*1.8?(nearest.dx>0?'Восточнее':'Западнее'):(nearest.dy>0?'Юго-':'Северо-')+(nearest.dx>0?'восточнее':'западнее')):null;card.append(el('h3',nearest?direction+' '+nearest.p.name:'Точка на карте'),el('p','Координаты: '+target.x.toFixed(4)+' / '+target.y.toFixed(4)),el('p',nearest?'Ближайший населённый пункт/крепость: '+nearest.p.name+' · '+(nearest.d/1000).toFixed(1)+' км':'Свободное перемещение с учётом дорог и зон местности.'));const actions=el('div');actions.className='map-point-actions';const walk=el('button','Идти пешком'),horse=el('button','На лошади'),cancel=el('button','Отмена');walk.onclick=ev=>{ev.stopPropagation();startTravel(target,'walk')};horse.onclick=ev=>{ev.stopPropagation();startTravel(target,'horse')};cancel.onclick=ev=>{ev.stopPropagation();freeTarget.classList.add('hidden');actionHost.replaceChildren()};actions.append(walk,horse,cancel);card.append(actions);actionHost.replaceChildren(card);onChange?.(state);paint();freeTarget.classList.remove('hidden');return}poiAuthoring.addFromEvent(e)};
   function syncEditorTools(){editorPanel.sync(editorMode);hint.textContent=editorMode==='road'?'Ставьте и соединяйте дорожные узлы. Тип местности определяется отдельными полигонами.':editorMode==='terrain'?'Неразмеченная территория имеет обычную скорость. Размечайте только зоны с модификатором; вершины выбранной зоны можно перетаскивать.':'Создавайте и перемещайте метки.'}
      back.onclick=()=>{MapViewSystem.world(state);mode='world';onChange?.(state);renderWorld()};
   if(!state.world.position?.pointId)state.world.position={regionId:'forest',pointId:'veligrad'};
   const existingTravel=TravelSystem.ensure(state);if(['travelling','event','stopped','camp'].includes(existingTravel.status)){lastTravelAt=performance.now();travelTimer=requestAnimationFrame(travelFrame)}
   paint();
   cleanup=()=>{poiAuthoring.destroy();editorSession.destroy();if(travelTimer)cancelAnimationFrame(travelTimer);travelTimer=null;frame.onclick=null;back.onclick=null;edit.onclick=null};
  }

  // --------------------------------------------------------------------------
  // LOCATION VIEW — renders location POIs and delegates editor tooling.
  // --------------------------------------------------------------------------
  function renderLocation(location){
   cleanup();onAudioContext('town');root.replaceChildren();
   const head=el('div');head.className='region-head';
   const back=el('button','← Регион');back.className='region-back';
   const title=el('div');title.append(el('h2',location.name),el('p','Карта локации'));
   const edit=el('button','Редактор');edit.className='region-edit-toggle';head.append(back,title,edit);root.append(head);
   const frame=el('div');frame.className='region-map-frame';
   const img=el('img');img.className='region-map-image';img.src=location.map;img.alt=location.name;frame.append(img);
   const layer=el('div');layer.className='region-poi-layer';frame.append(layer);root.append(frame);
   const actionHost=el('div');actionHost.className='map-point-action-host';root.append(actionHost);
   const localParty=el('div');localParty.className='party-marker';localParty.title='Ваш отряд';frame.append(localParty);
   const key='location:'+location.id;let editing=false,editorMode='poi',items=loadPoi(key),selected=current.placeId||current.districtId||null,editorSelected=null,drag=null;
   if(location.id==='veligrad'){if(!items.length){items=VELIGRAD.points.map(p=>({...p}));savePoi(key,items)}else{let changed=false;items=items.map(p=>{if(['gate','entrance','exit'].includes(p.class)||['gate','entrance','exit'].includes(p.type)){changed=true;return{...p,class:'transition',type:'transition'}}return p});if(changed)savePoi(key,items)}}
   const canonicalNavigation=location.id==='veligrad'?VELIGRAD_NAVIGATION:null;let roads=loadEditableRoads(key,canonicalNavigation||{nodes:[],edges:[],access:{}}),terrainZones=loadTerrainZones(key,canonicalNavigation?.terrainZones||[]);
   const editorSession=createMapEditorSession({root,frame,editButton:edit,kind:'location',panelOptions:{poiOptions:[['district','Район'],['place','Место'],['transition','Переход']],poiInitial:'district',poiPlaceholder:'Название',hintText:'Расставьте районы, места и точки перехода.',clearLabel:'Удалить все локальные метки'},roadMapId:key,terrainMapId:key,roads,zones:terrainZones,getPois:()=>items,getMode:()=>editorMode,setMode:value=>{editorMode=value;drag=null},getEditing:()=>editing,setEditing:value=>{editing=value},onPaint:paint,onModeChange:syncEditorTools,onRoadsChange:r=>{roads=r},onZonesChange:z=>{terrainZones=z},onRoadSelection:s=>{editorSession.panel.road.selection.textContent=s.nodeId?'Выбран узел: '+s.nodeId:s.edge?'Выбран участок: '+s.edge[0]+' → '+s.edge[1]:'Ничего не выбрано'},clearTerrainMessage:'Удалить все зоны местности этой локации?',clearRoadsMessage:'Удалить ВСЕ дорожные узлы и участки этой локации?'});
   const {panel:editorPanel,roadEditor}=editorSession;const {hint,poiSelection,removePoi,bindTransition}=editorPanel;
   function syncTransition(){const item=items.find(p=>p.id===editorSelected);bindTransition.disabled=!item||item.class!=='transition'}
   syncTransition();removePoi.onclick=()=>{const item=items.find(p=>p.id===editorSelected);if(item&&poiAuthoring.remove(item)){editorSelected=null;poiSelection.textContent='Метка не выбрана';removePoi.disabled=true;syncTransition()}};
   bindTransition.onclick=()=>{const item=items.find(p=>p.id===editorSelected);if(!item||item.class!=='transition')return;if(!roadEditor.bindTransition(location.id,item.id)){alert('Не удалось назначить точку перехода.');return}poiSelection.textContent='Точка перехода: '+item.name};
   const poiAuthoring=createPoiAuthoring({frame,panel:editorPanel,getItems:()=>items,setItems:value=>{items=value},persist:()=>persist(),getEditing:()=>editing,getMode:()=>editorMode,getDrag:()=>drag,setDrag:value=>{drag=value},createPoint:({choice,label,x,y,slug})=>{if(choice==='transition'&&items.some(p=>p.class==='transition'||p.type==='transition')){alert('У локации может быть только одна точка перехода.');return null}const resolved=label||({district:'Район',place:'Место',transition:'Переход'}[choice]);return{id:location.id+'-'+slug(resolved)+'-'+Date.now().toString(36),name:resolved,class:choice,type:choice,x,y}},exportFile:'location-'+location.id+'-poi.json',exportPayload:()=>({location:location.id,map:location.map,points:items}),resetConfirm:'Удалить все локальные метки этой локации?',resetItems:()=>[]});
   function persist(){savePoi(key,items);paint()}
   let travelTimer=null,lastTravelAt=0;
   function startLocalTravel(target,method='walk'){const t=LocationTravelSystem.start(state,{locationId:location.id,navigation:roads,points:{items,location},targetId:target.id,method});if(!t){actionHost.append(el('p','К этой точке пока нет доступного маршрута.'));return}SimulationSystem.setMode(state,'travel');lastTravelAt=performance.now();routeStatusLocal(t);if(!travelTimer)travelTimer=requestAnimationFrame(localTravelFrame);onChange?.(state);paintParty()}
   function routeStatusLocal(t){let msg=actionHost.querySelector('.map-route-status');if(!msg){msg=el('p');msg.className='quiet map-route-status';actionHost.append(msg)}msg.textContent=(t.status==='arrived'?'Прибыли · ':'В пути · ')+(Math.max(0,(t.distanceTotal||0)-(t.distanceDone||0))).toFixed(0)+' м'}
   function localTravelFrame(now){travelTimer=null;const t=TravelSystem.ensure(state);if(t.scope!=='location'||!['travelling','stopped','camp','event','arrived'].includes(t.status))return;const dt=Math.min(.1,Math.max(0,(now-(lastTravelAt||now))/1000));lastTravelAt=now;if(t.status==='travelling'){const before=t.distanceDone||0;LocationTravelSystem.tick(state,dt,roads,SimulationSystem.multiplier(state));if((t.distanceDone||0)>before)onChange?.(state);state.world.position={regionId:current.regionId,locationId:location.id,locationPointId:null,position:{...t.position}};paintParty();routeStatusLocal(t);if(t.status==='arrived'){const dest=LocationTravelSystem.arrive(state,items);if(dest)WorldSystem.enterMapPoint(state,dest);SimulationSystem.setMode(state,'world');const j=state.world?.journey;if(j?.status==='to-gate'&&dest?.id===j.gatePointId){const next=JourneySystem.continueFromGate(state,{locationNavigation:roads,regionalRoads:loadEditableRoads(view.regionId||current.regionId||'forest',CENTRAL_LANDS_ROADS),regionalPoints:loadPoi(view.regionId||current.regionId||'forest'),terrainZones:[]});if(next){const regionTrip=TravelSystem.start(state,{roads:loadEditableRoads(view.regionId||current.regionId||'forest',CENTRAL_LANDS_ROADS),points:loadPoi(view.regionId||current.regionId||'forest'),fromPosition:next.fromPosition,toId:j.targetId,method:j.method,terrainZones:[]});if(regionTrip){regionTrip.scope='region';regionTrip.regionId='forest';MapViewSystem.region(state,'forest');view.regionId='forest';view.locationId=null;mode='region';onChange?.(state);renderRegion('forest');return}}}onChange?.(state);paint();if(dest)showActions(dest);return}}travelTimer=requestAnimationFrame(localTravelFrame)}
   function showActions(item){actionHost.replaceChildren(actionPanel(item,state,(p,method)=>startLocalTravel(p,method),(p,b)=>{const favorite=WorldSystem.toggleFavorite(state,p);b.textContent=favorite?'★ В избранном':'☆ В избранное';onChange?.(state);paint()}))}
   function partyLocationPoint(){if(state.world?.position?.locationId!==location.id)return null;const id=state.world.position.locationPointId||current.placeId||current.districtId||location.spawnPointId;return items.find(p=>p.id===id)||items.find(p=>p.id===location.spawnPointId)||null}
   function paintParty(){const live=state.world?.position?.locationId===location.id&&state.world.position?.position;const p=live||partyLocationPoint();localParty.classList.toggle('hidden',!p);if(p){localParty.style.left=(p.x*100)+'%';localParty.style.top=(p.y*100)+'%'}}
   function paint(){layer.replaceChildren();for(const item of items){if(!editing&&!WorldSystem.isDiscovered(state,item))continue;const favorite=WorldSystem.isFavorite(state,item);const pin=el('button');pin.className='region-poi'+((editing||selected===item.id||favorite)?' expanded':'');if(editing&&editorSelected===item.id)pin.classList.add('editor-selected');pin.dataset.class=item.class;pin.style.left=(item.x*100)+'%';pin.style.top=(item.y*100)+'%';if(favorite)pin.classList.add('favorite');const dot=el('span','●');dot.className='point-symbol';const label=el('span',item.name||CLASSES[item.class]||'Место');label.className='point-label';pin.append(dot,label);if(favorite){const star=el('span','★');star.className='point-favorite';pin.append(star)};layer.append(pin);clampPin(pin,frame,item);
    pin.onclick=e=>{e.stopPropagation();if(editing&&editorMode!=='poi')return;if(editing){editorSelected=item.id;poiSelection.textContent='Выбрана метка: '+item.name+' · ID: '+item.id;removePoi.disabled=false;syncTransition();paint();return}selected=item.id;paint();showActions(item)};
    poiAuthoring.bindPin(pin,item)}paintParty()}
   frame.onclick=e=>{if(e.target.closest('.region-poi'))return;if(!editing){selected=null;WorldSystem.clearMapPoint(state);onChange?.(state);paint();return}poiAuthoring.addFromEvent(e)};
   function syncEditorTools(){editorPanel.sync(editorMode);hint.textContent=editorMode==='road'?'Ставьте и соединяйте дорожные узлы локации.':editorMode==='terrain'?'Неразмеченная территория имеет обычную скорость. Размечайте только местность с модификатором.':'Расставьте районы, места и точки перехода.'}
      back.onclick=()=>{MapViewSystem.region(state,view.regionId||current.regionId||'forest');onChange?.(state);mode='region';renderRegion(view.regionId||current.regionId||'forest')};
syncEditorTools();paint();const localTravel=TravelSystem.ensure(state);if(localTravel.scope==='location'&&localTravel.locationId===location.id&&['travelling','stopped','camp','event'].includes(localTravel.status)){lastTravelAt=performance.now();travelTimer=requestAnimationFrame(localTravelFrame)}
   cleanup=()=>{poiAuthoring.destroy();editorSession.destroy();if(travelTimer)cancelAnimationFrame(travelTimer);travelTimer=null;frame.onclick=null;back.onclick=null;edit.onclick=null};
  }

  if(mode==='location'){const location=CENTRAL_LANDS.points.find(p=>p.id===(view.locationId||current.locationId)&&p.map);if(location)renderLocation(location);else renderRegion(view.regionId||current.regionId||'forest')}else if(mode==='region')renderRegion(view.regionId||current.regionId||'forest');else renderWorld();
  return()=>cleanup();
 }
};
