import {createId} from './ids.js';
import {createRngSet} from './rng.js';
export const STATE_VERSION=2;
export function createGameState({worldName='Новый мир',seed=Date.now()}={}){
 const worldId=createId('world'),playerId=createId('player'),now=new Date().toISOString();
 return {modules:{campaign:{enabled:true},combat:{enabled:false},'combat-lab':{enabled:false}},meta:{stateVersion:STATE_VERSION,saveVersion:1,gameVersion:null,worldId,worldName:String(worldName).trim().slice(0,48)||'Новый мир',seed,createdAt:now,updatedAt:now},clock:{day:1,minute:480},session:{hostPlayerId:playerId,players:{[playerId]:{id:playerId,controlledEntities:[]}},party:{leaderPlayerId:playerId,members:[]}},entities:{characters:{},items:{},containers:{}},world:{locations:{}},ui:{mapView:{level:'world',regionId:null,locationId:null}},relations:{},factions:{},quests:{},simulation:{},rng:createRngSet(seed),history:[]};
}
export function validateGameState(s){const errors=[];if(!s||typeof s!=='object')return {ok:false,errors:['State must be an object']};if(!s.meta?.worldId)errors.push('meta.worldId missing');if(!s.meta?.worldName)errors.push('meta.worldName missing');if(!Number.isInteger(s.clock?.day)||s.clock.day<1)errors.push('clock.day invalid');if(!Number.isFinite(s.clock?.minute)||s.clock.minute<0||s.clock.minute>=1440)errors.push('clock.minute invalid');const host=s.session?.hostPlayerId;if(!host||!s.session?.players?.[host])errors.push('host player invalid');if(!Array.isArray(s.session?.party?.members))errors.push('party.members invalid');for(const key of ['characters','items','containers'])if(!s.entities?.[key]||typeof s.entities[key]!=='object')errors.push('entities.'+key+' invalid');if(!s.rng?.world||!s.rng?.combat||!s.rng?.loot||!s.rng?.simulation)errors.push('rng streams invalid');return {ok:errors.length===0,errors}}
export function cloneState(state){return structuredClone(state)}
