import {TravelConditions} from './conditions.js';
import {buildTravelGraph,fastestPath,alternativePaths,freeTravelPath} from './route-planner.js';
function metric(roads,a,b){const m=roads.metrics||{widthMeters:1,heightMeters:1},dx=(b.x-a.x)*m.widthMeters,dy=(b.y-a.y)*m.heightMeters;return Math.hypot(dx,dy)}
function length(roads,path){let n=0;for(let i=1;i<path.length;i++)n+=metric(roads,path[i-1],path[i]);return n}
function closestOnSegment(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return{...a,t:0,distance:Math.hypot(p.x-a.x,p.y-a.y)};const t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l)),q={x:a.x+dx*t,y:a.y+dy*t};return{...q,t,distance:Math.hypot(p.x-q.x,p.y-q.y)}}
function v2Graph(roads,method='walk',terrainZones=[]){const nodes=new Map((roads.nodes||[]).map(n=>[n.id,n])),g=buildTravelGraph(roads,nodes,method,terrainZones);return{nodes,g}}
function shortest(g,from,to){return fastestPath(g,from,to)}
function offRoadCost(roads,path,method,zones){return TravelConditions.traversalCost(roads,path,{roadType:'rough',terrain:'plain'},method,zones)}
export const RoadSystem={
 graph(roads,method='walk',terrainZones=[]){return v2Graph(roads,method,terrainZones).g},
 route(roads,points,fromId,toId,method='walk',terrainZones=[]){const {nodes,g}=v2Graph(roads,method,terrainZones),a=roads.access?.[fromId],b=roads.access?.[toId],pa=points.find(p=>p.id===fromId),pb=points.find(p=>p.id===toId);if(!a||!b||!pa||!pb)return null;const core=shortest(g,a.node,b.node);if(!core)return null;const na=nodes.get(a.node),nb=nodes.get(b.node),poly=[pa,na,...core.polyline.slice(1),pb],d=length(roads,poly);return{fromId,toId,nodeIds:[fromId,...core.nodeIds,toId],roadNodeIds:core.nodeIds,segments:core.segments,polyline:poly,distance:d,cost:core.cost}},
 nearestRoadPoint(roads,pos){const {nodes}=v2Graph(roads);let best=null;for(const [a,b] of roads.edges||[]){const pa=nodes.get(a),pb=nodes.get(b);if(!pa||!pb)continue;const q=closestOnSegment(pos,pa,pb);if(!best||q.distance<best.distance)best={...q,a,b}}return best},
 routeBetweenPositions(roads,start,end,method='walk',terrainZones=[]){if(!start||!end)return null;const core=freeTravelPath(roads,start,end,method,terrainZones);if(!core)return null;const firstRoad=core.segments.find(x=>x.kind==='road'),firstIndex=firstRoad?core.segments.indexOf(firstRoad):-1,entryDistance=firstIndex>0?core.segments.slice(0,firstIndex).reduce((n,x)=>n+x.distance,0):0;return{fromId:'free-position',toId:'free-position',nodeIds:core.nodeIds,roadNodeIds:core.nodeIds.filter(id=>!id.startsWith('@')),segments:core.segments,polyline:core.polyline,distance:core.distance,cost:core.cost,roadEntry:firstRoad?{node:firstRoad.from,entryDistance}:null}},
 routeFromPosition(roads,points,pos,toId,method='walk',terrainZones=[]){const dest=points.find(p=>p.id===toId);if(!dest)return null;const route=this.routeBetweenPositions(roads,pos,dest,method,terrainZones);return route?{...route,toId,nodeIds:['free-position',...route.nodeIds.slice(1,-1),toId]}:null},
 routes(roads,points,fromId,toId,method='walk',limit=3,terrainZones=[]){const {nodes,g}=v2Graph(roads,method,terrainZones),a=roads.access?.[fromId],b=roads.access?.[toId],pa=points.find(p=>p.id===fromId),pb=points.find(p=>p.id===toId);if(!a||!b||!pa||!pb)return[];return alternativePaths(g,a.node,b.node,limit).map(core=>{const na=nodes.get(a.node),nb=nodes.get(b.node),poly=[pa,na,...core.polyline.slice(1),pb];return{fromId,toId,nodeIds:[fromId,...core.nodeIds,toId],roadNodeIds:core.nodeIds,segments:core.segments,polyline:poly,distance:length(roads,poly),cost:core.cost}})},
 distance(roads,a,b){return metric(roads,a,b)},polylineLength(roads,p){return length(roads,p)}
};
