import {buildTravelGraph,fastestPath,alternativePaths} from './route-planner.js';
function metric(roads,a,b){const m=roads.metrics||{widthMeters:1,heightMeters:1},dx=(b.x-a.x)*m.widthMeters,dy=(b.y-a.y)*m.heightMeters;return Math.hypot(dx,dy)}
function length(roads,path){let n=0;for(let i=1;i<path.length;i++)n+=metric(roads,path[i-1],path[i]);return n}
function closestOnSegment(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return{...a,t:0,distance:Math.hypot(p.x-a.x,p.y-a.y)};const t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l)),q={x:a.x+dx*t,y:a.y+dy*t};return{...q,t,distance:Math.hypot(p.x-q.x,p.y-q.y)}}
function v2Graph(roads,method='walk',terrainZones=[]){const nodes=new Map((roads.nodes||[]).map(n=>[n.id,n])),g=buildTravelGraph(roads,nodes,method,terrainZones);return{nodes,g}}
function shortest(g,from,to){return fastestPath(g,from,to)}
export const RoadSystem={
 graph(roads,method='walk',terrainZones=[]){return v2Graph(roads,method,terrainZones).g},
 route(roads,points,fromId,toId,method='walk',terrainZones=[]){const {nodes,g}=v2Graph(roads,method,terrainZones),a=roads.access?.[fromId],b=roads.access?.[toId],pa=points.find(p=>p.id===fromId),pb=points.find(p=>p.id===toId);if(!a||!b||!pa||!pb)return null;const core=shortest(g,a.node,b.node);if(!core)return null;const na=nodes.get(a.node),nb=nodes.get(b.node),poly=[pa,na,...core.polyline.slice(1),pb],d=length(roads,poly);return{fromId,toId,nodeIds:[fromId,...core.nodeIds,toId],roadNodeIds:core.nodeIds,segments:core.segments,polyline:poly,distance:d,cost:core.cost}},
 nearestRoadPoint(roads,pos){const {nodes}=v2Graph(roads);let best=null;for(const [a,b] of roads.edges||[]){const pa=nodes.get(a),pb=nodes.get(b);if(!pa||!pb)continue;const q=closestOnSegment(pos,pa,pb);if(!best||q.distance<best.distance)best={...q,a,b}}return best},
 routeFromPosition(roads,points,pos,toId,method='walk',terrainZones=[]){const snap=this.nearestRoadPoint(roads,pos),target=roads.access?.[toId],dest=points.find(p=>p.id===toId);if(!snap||!target||!dest)return null;const {nodes,g}=v2Graph(roads,method,terrainZones),choices=[];for(const start of [snap.a,snap.b]){const core=shortest(g,start,target.node);if(core){const startNode=nodes.get(start);choices.push({core,start,cost:metric(roads,snap,startNode)+core.cost})}}choices.sort((a,b)=>a.cost-b.cost);const c=choices[0];if(!c)return null;const startNode=nodes.get(c.start),endNode=nodes.get(target.node),entry=[{...pos},{x:snap.x,y:snap.y},{x:startNode.x,y:startNode.y}],poly=[...entry,...c.core.polyline.slice(1),{x:endNode.x,y:endNode.y},{x:dest.x,y:dest.y}],entryDistance=length(roads,entry);return{fromId:'road-position',toId,nodeIds:['road-position',c.start,...c.core.nodeIds.slice(1),toId],roadNodeIds:[c.start,...c.core.nodeIds.slice(1)],segments:c.core.segments,polyline:poly,distance:length(roads,poly),roadEntry:{x:snap.x,y:snap.y,edge:[snap.a,snap.b],node:c.start,entryDistance},cost:c.cost}},
 routes(roads,points,fromId,toId,method='walk',limit=3,terrainZones=[]){const {nodes,g}=v2Graph(roads,method,terrainZones),a=roads.access?.[fromId],b=roads.access?.[toId],pa=points.find(p=>p.id===fromId),pb=points.find(p=>p.id===toId);if(!a||!b||!pa||!pb)return[];return alternativePaths(g,a.node,b.node,limit).map(core=>{const na=nodes.get(a.node),nb=nodes.get(b.node),poly=[pa,na,...core.polyline.slice(1),pb];return{fromId,toId,nodeIds:[fromId,...core.nodeIds,toId],roadNodeIds:core.nodeIds,segments:core.segments,polyline:poly,distance:length(roads,poly),cost:core.cost}})},
 distance(roads,a,b){return metric(roads,a,b)},polylineLength(roads,p){return length(roads,p)}
};
