import {RoadSystem} from './roads.js';
import {PauseSystem} from '../pause.js';
import {runtimeTrace} from '../../diagnostics/runtime-trace.js';
import {TravelConditions} from './conditions.js';
const SPEED={walk:84,horse:180};
function metrics(roads,polyline){const lengths=[];let total=0;for(let i=1;i<(polyline?.length||0);i++){const n=RoadSystem.distance(roads,polyline[i-1],polyline[i]);lengths.push(n);total+=n}return{lengths,total}}
function atDistance(roads,polyline,distance){if(!polyline?.length)return null;if(polyline.length===1)return{...polyline[0]};const {lengths,total}=metrics(roads,polyline);let target=Math.max(0,Math.min(total,distance));for(let i=0;i<lengths.length;i++){if(target<=lengths[i]){const a=polyline[i],b=polyline[i+1],q=lengths[i]?target/lengths[i]:0;return{x:a.x+(b.x-a.x)*q,y:a.y+(b.y-a.y)*q}}target-=lengths[i]}return{...polyline.at(-1)}}
function anchor(route,pos){const e=route?.roadEntry;if(!e)return null;return{id:'temporary-road-position',position:{...pos},targetNode:e.node,edge:e.edge,entryDistance:e.entryDistance||0,temporary:true}}
function makeFromPosition(roads,points,pos,toId,method='walk'){const route=RoadSystem.routeFromPosition(roads,points,pos,toId,method);return route?{route,tempAnchor:anchor(route,pos)}:null}
export const TravelSystem={
 ensure(state){state.world=state.world||{};state.world.travel=state.world.travel||{status:'idle'};return state.world.travel},
 start(state,{roads,points,fromId,toId,method='walk',fromPosition=null}){const trace=runtimeTrace.begin('travel.start',{fromId,toId,method,fromPosition});let route,tempAnchor=null;if(fromPosition){const r=makeFromPosition(roads,points,fromPosition,toId,method);route=r?.route;tempAnchor=r?.tempAnchor||null}else route=RoadSystem.route(roads,points,fromId,toId,method);if(!route){runtimeTrace.end(trace,{ok:false,reason:'no-route'});return null}const travelFactor=TravelConditions.routeFactor(route,method);const t={status:'travelling',regionId:roads.regionId,fromId:fromPosition?'road-position':fromId,toId,method,route,travelFactor,position:{...route.polyline[0]},distanceDone:0,distanceTotal:route.distance,tempAnchor};state.world.travel=t;runtimeTrace.end(trace,{ok:true,distanceMeters:route.distance,nodeIds:route.nodeIds,tempAnchor});return t},
 tick(state,deltaSeconds,roads,gameSpeed=1){const t=this.ensure(state);if(t.status!=='travelling'||PauseSystem.isPaused(state))return t;const move=Math.max(0,deltaSeconds)*Math.max(1,gameSpeed)*(SPEED[t.method]||SPEED.walk)*(t.travelFactor||TravelConditions.routeFactor(t.route,t.method));t.distanceTotal=t.route?.distance||0;t.distanceDone=Math.min(t.distanceTotal,(t.distanceDone||0)+move);t.position=atDistance(roads,t.route.polyline,t.distanceDone);t.progress=t.distanceTotal?t.distanceDone/t.distanceTotal:1;if(t.tempAnchor&&t.distanceDone>=t.tempAnchor.entryDistance)t.tempAnchor=null;if(t.progress>=1){t.status='arrived';runtimeTrace.animation('travel.arrived',{toId:t.toId,position:t.position,distanceMeters:t.distanceTotal})}return t},
 stop(state,{roads,points}={}){const t=this.ensure(state);runtimeTrace.system('travel.stop','invoke',{status:t.status,position:t.position});if(t.status==='travelling'){t.status='stopped';const r=roads&&points&&t.position?makeFromPosition(roads,points,t.position,t.toId,t.method):null;if(r)t.tempAnchor=r.tempAnchor}return t},
 resume(state,{roads,points}={}){const t=this.ensure(state);runtimeTrace.system('travel.resume','invoke',{status:t.status,position:t.position});if((t.status==='stopped'||t.status==='camp')&&roads&&points&&t.position){const r=makeFromPosition(roads,points,t.position,t.toId,t.method);if(r){t.route=r.route;t.distanceDone=0;t.distanceTotal=r.route.distance;t.travelFactor=TravelConditions.routeFactor(r.route,t.method);t.tempAnchor=r.tempAnchor}}if(t.status==='stopped'||t.status==='camp')t.status='travelling';return t},
 camp(state,{roads,points}={}){const t=this.ensure(state);runtimeTrace.system('travel.camp','invoke',{status:t.status,position:t.position});if(t.position){t.status='camp';const r=roads&&points?makeFromPosition(roads,points,t.position,t.toId,t.method):null;if(r)t.tempAnchor=r.tempAnchor;state.world.camp={regionId:t.regionId,position:{...t.position},createdAt:{day:state.clock.day,minute:state.clock.minute}}}return t},
 pauseForEvent(state,eventId){const t=this.ensure(state);if(t.status==='travelling')t.status='event';t.eventId=eventId||null;PauseSystem.set(state,'event',true);return t},
 resumeEvent(state){const t=this.ensure(state);PauseSystem.set(state,'event',false);if(t.status==='event'){t.status='travelling';t.eventId=null}return t},
 cancel(state,{roads,points}={}){const t=this.ensure(state);runtimeTrace.system('travel.cancel','invoke',{status:t.status,position:t.position});let tempAnchor=t.tempAnchor||null;if(roads&&points&&t.position&&t.toId){const r=makeFromPosition(roads,points,t.position,t.toId,t.method);if(r)tempAnchor=r.tempAnchor}if(t.position)state.world.position={regionId:t.regionId,pointId:null,position:{...t.position},tempAnchor};state.world.travel={status:'idle',position:t.position?{...t.position}:null,regionId:t.regionId||null,tempAnchor};return state.world.travel},
 progress(state){const t=this.ensure(state),total=t.distanceTotal||t.route?.distance||0,done=t.distanceDone||0;return{done,total,left:Math.max(0,total-done),ratio:total?done/total:0}}
};
