import {RoadSystem} from './roads.js';
import {PauseSystem} from '../pause.js';
import {runtimeTrace} from '../../diagnostics/runtime-trace.js';
import {TravelConditions} from './conditions.js';
import {TerrainSystem} from '../../map/terrain.js';
import {accessPorts} from '../../map/access-points.js';
const SPEED={walk:84,horse:180};
function metric(roads,a,b){return RoadSystem.distance(roads,a,b)}
function buildLegs(roads,route,method,zones=[]){
 const legs=[];const add=(a,b,roadType='rough',fallback='plain')=>{const distance=metric(roads,a,b);if(!distance)return;const spans=zones.length?TerrainSystem.segmentSpans(zones,a,b):[{terrain:fallback,fraction:1,passable:true}];let cursor={...a};for(const s of spans){const end={x:cursor.x+(b.x-a.x)*s.fraction,y:cursor.y+(b.y-a.y)*s.fraction};const factor=TravelConditions.factor(roadType,s.terrain,method);if(!factor)throw new Error('Impassable travel leg');legs.push({from:{...cursor},to:{...end},distance:distance*s.fraction,factor,roadType,terrain:s.terrain});cursor=end}};
 const segments=route?.segments||[];if(!segments.length){for(let i=1;i<(route?.polyline?.length||0);i++)add(route.polyline[i-1],route.polyline[i]);return legs}
 const first=segments[0]?.path?.[0],last=segments.at(-1)?.path?.at(-1),poly=route.polyline||[];let i=0;
 while(i<poly.length-1&&first&&(poly[i].x!==first.x||poly[i].y!==first.y)){add(poly[i],poly[i+1]);i++}
 for(const s of segments)for(let j=1;j<s.path.length;j++)add(s.path[j-1],s.path[j],s.roadType,s.terrain);
 let endIndex=poly.findIndex(p=>last&&p.x===last.x&&p.y===last.y);if(endIndex>=0)for(let j=endIndex+1;j<poly.length;j++)add(poly[j-1],poly[j]);
 return legs
}
function positionOnLeg(leg,d){const q=leg.distance?Math.max(0,Math.min(1,d/leg.distance)):1;return{x:leg.from.x+(leg.to.x-leg.from.x)*q,y:leg.from.y+(leg.to.y-leg.from.y)*q}}
function anchor(route,pos){const e=route?.roadEntry;if(!e)return null;return{id:'temporary-road-position',position:{...pos},targetNode:e.node,edge:e.edge,entryDistance:e.entryDistance||0,temporary:true}}
function makeFromPosition(roads,points,pos,toId,method='walk',terrainZones=[]){const route=RoadSystem.routeFromPosition(roads,points,pos,toId,method,terrainZones);return route?{route,tempAnchor:anchor(route,pos)}:null}
function prepare(t,roads,zones=[]){t.terrainZones=zones;t.legs=buildLegs(roads,t.route,t.method,zones);t.legIndex=0;t.legDistance=0;t.distanceDone=0;t.distanceTotal=t.legs.reduce((n,l)=>n+l.distance,0);t.travelCost=t.legs.reduce((n,l)=>n+l.distance/l.factor,0);t.etaSeconds=t.travelCost/(SPEED[t.method]||SPEED.walk);t.position=t.legs[0]?{...t.legs[0].from}:{...t.route.polyline[0]};return t}
export const TravelSystem={
 ensure(state){state.world=state.world||{};state.world.travel=state.world.travel||{status:'idle'};return state.world.travel},
 start(state,{roads,points,fromId=null,toId=null,method='walk',fromPosition=null,toPosition=null,terrainZones=[]}){const effectiveFromId=fromPosition?'free-position':(fromId||'free-position'),start=fromPosition||points?.find(p=>p.id===fromId),logicalEnd=toPosition||points?.find(p=>p.id===toId);const trace=runtimeTrace.begin('travel.start',{fromId:effectiveFromId,toId,method,fromPosition,start,end:logicalEnd});if(!start||!logicalEnd){runtimeTrace.end(trace,{ok:false,reason:'missing-endpoint'});return null}let chosen=null;const ports=toPosition?[]:accessPorts(roads,toId),nodes=new Map((roads.nodes||[]).map(n=>[n.id,n]));const candidates=ports.map(port=>({port,end:nodes.get(port.node)})).filter(x=>x.end);if(!candidates.length)candidates.push({port:null,end:logicalEnd});for(const candidate of candidates){const route=RoadSystem.routeBetweenPositions(roads,start,candidate.end,method,terrainZones);if(!route)continue;const score=route.distance??Infinity;if(!chosen||score<chosen.score)chosen={route,end:candidate.end,port:candidate.port,score}}if(!chosen){runtimeTrace.end(trace,{ok:false,reason:'no-route'});return null}const {route,end,port}=chosen;route.fromId=effectiveFromId;route.toId=toId||'free-position';route.toPortId=port?.id||null;const tempAnchor=anchor(route,start),t=prepare({status:'travelling',regionId:roads.regionId,fromId:effectiveFromId,toId:toId||null,toPortId:port?.id||null,targetPosition:{x:end.x,y:end.y},method,route,tempAnchor},roads,terrainZones);state.world.travel=t;runtimeTrace.end(trace,{ok:true,distanceMeters:t.distanceTotal,etaSeconds:t.etaSeconds,nodeIds:route.nodeIds,tempAnchor});return t},
 tick(state,deltaSeconds,roads,gameSpeed=1){const t=this.ensure(state);if(t.status!=='travelling'||PauseSystem.isPaused(state))return t;if(!t.legs?.length)prepare(t,roads,t.terrainZones||[]);let time=Math.max(0,deltaSeconds)*Math.max(1,gameSpeed),base=SPEED[t.method]||SPEED.walk;while(time>0&&t.legIndex<t.legs.length){const leg=t.legs[t.legIndex],left=leg.distance-t.legDistance,speed=base*leg.factor,need=left/speed;if(time>=need){t.distanceDone+=left;t.legIndex++;t.legDistance=0;time-=need;t.position={...leg.to}}else{const move=time*speed;t.legDistance+=move;t.distanceDone+=move;t.position=positionOnLeg(leg,t.legDistance);time=0}}t.progress=t.distanceTotal?t.distanceDone/t.distanceTotal:1;if(t.tempAnchor&&t.distanceDone>=t.tempAnchor.entryDistance)t.tempAnchor=null;if(t.legIndex>=t.legs.length){t.status='arrived';t.progress=1;runtimeTrace.animation('travel.arrived',{toId:t.toId,position:t.position,distanceMeters:t.distanceTotal})}return t},
 stop(state,{roads,points,terrainZones=[]}={}){const t=this.ensure(state);runtimeTrace.system('travel.stop','invoke',{status:t.status,position:t.position});if(t.status==='travelling'){t.status='stopped';const r=roads&&points&&t.position?makeFromPosition(roads,points,t.position,t.toId,t.method,terrainZones):null;if(r)t.tempAnchor=r.tempAnchor}return t},
 resume(state,{roads,points,terrainZones=[]}={}){const t=this.ensure(state);runtimeTrace.system('travel.resume','invoke',{status:t.status,position:t.position});if((t.status==='stopped'||t.status==='camp')&&roads&&points&&t.position){const r=makeFromPosition(roads,points,t.position,t.toId,t.method,terrainZones);if(r){t.route=r.route;t.tempAnchor=r.tempAnchor;prepare(t,roads,terrainZones)}}if(t.status==='stopped'||t.status==='camp')t.status='travelling';return t},
 camp(state,{roads,points,terrainZones=[]}={}){const t=this.ensure(state);runtimeTrace.system('travel.camp','invoke',{status:t.status,position:t.position});if(t.position){t.status='camp';const r=roads&&points?makeFromPosition(roads,points,t.position,t.toId,t.method,terrainZones):null;if(r)t.tempAnchor=r.tempAnchor;state.world.camp={regionId:t.regionId,position:{...t.position},createdAt:{day:state.clock.day,minute:state.clock.minute}}}return t},
 pauseForEvent(state,eventId){const t=this.ensure(state);if(t.status==='travelling')t.status='event';t.eventId=eventId||null;PauseSystem.set(state,'event',true);return t},
 resumeEvent(state){const t=this.ensure(state);PauseSystem.set(state,'event',false);if(t.status==='event'){t.status='travelling';t.eventId=null}return t},
 cancel(state,{roads,points,terrainZones=[]}={}){const t=this.ensure(state);runtimeTrace.system('travel.cancel','invoke',{status:t.status,position:t.position});let tempAnchor=t.tempAnchor||null;if(roads&&points&&t.position&&t.toId){const r=makeFromPosition(roads,points,t.position,t.toId,t.method,terrainZones);if(r)tempAnchor=r.tempAnchor}if(t.position)state.world.position={regionId:t.regionId,pointId:null,position:{...t.position},tempAnchor};state.world.travel={status:'idle',position:t.position?{...t.position}:null,regionId:t.regionId||null,tempAnchor};return state.world.travel},
 arrive(state){const t=this.ensure(state);if(t.status!=='arrived'||t.scope==='location')return null;const position=t.toId?{regionId:t.regionId,pointId:t.toId,...(t.toPortId?{entryPortId:t.toPortId}:{})}:{regionId:t.regionId,pointId:null,position:t.position?{...t.position}:null};state.world.position=position;return position},\n progress(state){const t=this.ensure(state),total=t.distanceTotal||t.route?.distance||0,done=t.distanceDone||0;return{done,total,left:Math.max(0,total-done),ratio:total?done/total:0,etaSeconds:t.etaSeconds||null}}
};
